### ISSUE TITLE
Is rendering .md in <iframe> possible?

### ISSUE THREAD

**Issue by defdefred** [simov/markdown-viewer#102]
example:

<!DOCTYPE html>
<html>
<body>
<iframe name="menu" width="128" src="menu.md">
  <p>Your browser does not support iframes.</p>
</iframe>
</iframe><iframe name="article" src="welcome.md">
  <p>Your browser does not support iframes.</p>
</iframe>

</body>
</html>

**Comment by simov** [comment]
I don't think that's currently possible.

**Comment by simov** [comment]
Duplicate of https://github.com/simov/markdown-viewer/issues/83
