### ISSUE TITLE
TOC does not work if there is a '<' sign in a header

### ISSUE THREAD

**Issue by ben-woolnough** [simov/markdown-viewer#103]
Test with this: https://raw.githubusercontent.com/RobinHerbots/Inputmask/5.0.0/README.md

The table of contents stops after the less than sign in the header 'Classic web with <script> tag' so the last entry in the TOC reads 'Classic web with'.

Changing the compiler does not fix this.

**Comment by simov** [comment]
Thanks for reporting, I'll have a look.

**Comment by simov** [comment]
Fixed and published in v3.8
