### ISSUE TITLE
linked css not working, only working if copied

### ISSUE THREAD

**Issue by DoctorSubtilis** [simov/markdown-viewer#107]
So far (3.7) I was able to link from my home to extension folder a css. Now, with 3.8, a _linked_ css is working no more: it works only if _copied_ in themes folder: why?
Thank you

**Comment by simov** [comment]
You mean symbolic link on your file system? Browser extensions doesn't have control over how files are read from your local system, it's the browser itself that allows and controls that.

**Comment by DoctorSubtilis** [comment]
Yes, symlinks.  
No, I'm not sure if it depends from a browser update: what broser's settings I should check?

**Comment by simov** [comment]
I don't know, but this is most likely a breaking change in Chrome after update. There is no way for a browser extension to check for symlinks, at least that I know of.

**Comment by DoctorSubtilis** [comment]
ok, thank you

**Comment by DoctorSubtilis** [comment]
Today I found a workaround: put within the css (in Chomium extension folder) a link toward my css:
    `@import url(http://localhost/path-to-my-file/myfile.css`  

### another small question  
So it works, but I noticed that **the left toc div** (in chromium window) isn't affected by css (even I use #_toc)  

Thanks

**Comment by simov** [comment]
I'm probably using some really heavy css rules there, like `!important` on a `#` selector, check out the `.css` files in the repo, you should be able to style it with the correct selector + using `!important`.

**Comment by DoctorSubtilis** [comment]
Thank you. Already done, but unsuccessfully (as in attacde image):
`#_toc-left #_toc {background-image: linear-gradient(to right, #d9d9d9,#e6e6e6 80%) !important; color: white;}`
![Screenshot_20200403_102834](https://user-images.githubusercontent.com/20089138/78340242-0bb24c80-7596-11ea-92f1-629f0d6db4a0.png)  
Probably this is due to tha fact that ""#_toc" division (the left one), unlike "#_html" div (at right side), doesn't have the class class="markdown-theme" (applied from Chromium: customizable?)

**Comment by simov** [comment]
Your selector isn't correct `._toc-left` is a class, although you probably don't need this, check out the TOC styles here https://github.com/simov/markdown-viewer/blob/master/content/index.css#L56-L92

**Comment by DoctorSubtilis** [comment]
Thank you. I tried with:  
`#_toc {background: transparent !important; background-image: linear-gradient(to right, #d9d9d9,#e6e6e6 80%) !important; color: white !important;}`
but unsuccessfully.
Using "inspect", as I said, I see that to "#_toc" **isn't applied the class "markdown-theme"**: this is the problem, I guess. I don't know if this is your "guilt", so to say, or Chromium...

**Comment by DoctorSubtilis** [comment]
Sorry: the problem was the Chromium **cache**!
Now it works (at least it seems)!
