### ISSUE TITLE
favicon not visible in darkmode on browser toolbar

### ISSUE THREAD

**Issue by py563** [simov/markdown-viewer#121]
please change favicon from black to some other color, i assume it is simply 'm' in Roboto Medium Italic Font.
![logo](https://vectr.com/tmp/b2ca7ckT2k/b1SKXhtPOU.svg?width=84.92&height=120&select=hJ99v7NSS&source=selection)

**Comment by simov** [comment]
Yes, I know about this issue .. btw which browser do you use?

**Comment by py563** [comment]
edge chromium and brave

**Comment by simov** [comment]
Markdown Viewer v5 got released with light icon support for dark browser themes. The option is a little bit hidden, so make sure you have a look at the updated screencast on the extension's listing page in Chrome Web Store.

**Comment by cvladan** [comment]
> Markdown Viewer v5 got released with light icon support for dark browser themes. The option is a little bit hidden, so make sure you have a look at the updated screencast on the extension's listing page in Chrome Web Store.

Does this also work in Firefox?
Right now, I can't find that option in the same place as in Chrome
