### ISSUE TITLE
Problem with Greek

### ISSUE THREAD

**Issue by strigkos** [simov/markdown-viewer#122]
Very nice app, but there is a small problem with Greek characters
while other applications ( e.g. MarkView ) don't have this problem
Thank you

**Comment by simov** [comment]
What exactly is the issue that you are having? Can you share a screenshot or a code snippet that I can use to reproduce it?

**Comment by strigkos** [comment]
Yes
Thanks for the replay
[image: image.png]
your  plugin  online file
http://342340261.linuxzone19.grserver.gr/%CE%93%CE%B9%CF%8E%CF%81%CE%B3%CE%BF%CF%82.md


---

[image: image.png]
your plugin - local file ( C: )

-----

file content

Για Ιούλιο
==========
- Videos ( *2 )
ένα για επαγγελματίες, ένα για πελάτες
- Instagram
- Facebook
- YouTube
- Λογιστικά

Για Αύγουστο
============
- Λογιστικά
- Τιμολόγια

geofregg@yahoo.gr


-------------

The problem is a combination with Chrome bad functionality about Encoding
This also happens with *.txt files
But the plugin below somehow works correctly


[image: image.png]

**Comment by strigkos** [comment]
...and this plugin
[image: image.png]
also solves the Encoding problem for txt extension files (Without encoding
tag)

**Comment by simov** [comment]
That's interesting because after you enable the origin there is an Encoding option for it, that you can use for those cases, but apparently it doesn't work with this server. I have to take a look.

**Comment by simov** [comment]
Let me know if this is still an issue.
