### ISSUE TITLE
Markdown viewer not rendering?

### ISSUE THREAD

**Issue by mikejhuang** [simov/markdown-viewer#123]
![image](https://user-images.githubusercontent.com/10882060/83064716-d2c5be00-a094-11ea-84c5-0be89ebcd6a6.png)

I don't know if I'm just stupid and don't know how to activate it, but I clicked through the settings and nothing I toggle seems to make my markdown file render. Could someone help me figure this out?

**Comment by simov** [comment]
Hi @mikejhuang can you check this and see if it works for you https://github.com/simov/markdown-viewer#local-files

Note that you have to enable two separate switches.

**Comment by mikejhuang** [comment]
Hey it worked, I needed to enable file urls. Thank you. I didn't see the instructions when installing this through the Chrome store.
