### ISSUE TITLE
Problem with spaces as new-line after bold/italics followed by a period

### ISSUE THREAD

**Issue by fditolla** [simov/markdown-viewer#124]
With the following test data (all lines are terminated by two spaces), line 1 and 5 do not comply with the 2 spaces rule=new-line:
--- test data start ---  
line 1 \*\*bold follwed by period\*\*.  
line 2  
line 3 \*\*bold\*\*  
line 4  
line 5 \*italic follwed by period\*.  
line 6  
line 7 \*italic\*  
line 8  
line 9 text followed by period.  
line 10  
line 11 text  
line 12  
--- end ---
in markdown viewer 3.9 in Chrome  83.0.4103.106 this is rendered as follows:
--- markdown viewer 3.9 rendering start ---  
line 1 **bold follwed by period**.  line 2  
line 3 **bold**  
line 4  
line 5 *italic follwed by period*. line 6  
line 7 *italic*  
line 8
line 9 text followed by period.  
line 10  
line 11 text  
line 12  
--- end ---

**Comment by simov** [comment]
Ok, I was able to reproduce it, though it's worth noting that the issue is present only when using the `Marked` compiler, and when the `breaks` option turned off.

A better place to post this issue is on the [marked](https://github.com/markedjs/marked) issue tracker instead.

**Comment by fditolla** [comment]
ok thanks I'll open it there.

**Comment by simov** [comment]
Also in case they ask you about specific Marked version that you use, you can take it from [here](https://github.com/simov/markdown-viewer/blob/master/package.json#L20). Probably there is a comment in the `vendor` folder as well.
