### ISSUE TITLE
Blank line in code block breaks rendering

### ISSUE THREAD

**Issue by wwalker** [simov/markdown-viewer#125]
Using Github Dark (didn't test with other modes).

If a code block immediately follows a bullet list item, and that code clock has a blank line in it, markdown-viewer closes the code block at the blank line.

If there is a blank line between the bullet list item and the code block, it renders as not belonging to the bullet list item (i.e., the code block is not indented), but the entire code block is properly included in the code block div.  Interestingly the "indented code block behavior (which I prefer) does not occur on github.com.

With or without the blank line following the bullet list item, the code block renders correctly on github.com.

**Comment by wwalker** [comment]
This files exhibits the described behavior:

[ThePlan.md.gz](https://github.com/simov/markdown-viewer/files/4974866/ThePlan.md.gz)
![github-ThePlan md](https://user-images.githubusercontent.com/23478/88448129-ea54c500-cdff-11ea-96a0-63e52b19b0f1.png)
![markdown-viewer-ThePlan md](https://user-images.githubusercontent.com/23478/88448130-eaed5b80-cdff-11ea-8f93-86af776de1fd.png)

**Comment by wwalker** [comment]
Here it is in the default github scheme.
![markdown-viewer-ThePlan md-light](https://user-images.githubusercontent.com/23478/88448227-191f6b00-ce01-11ea-81c5-4d82f4f110aa.png)

**Comment by simov** [comment]
Hi @wwalker, can you paste the raw markdown snippet here?

**Comment by wwalker** [comment]
https://gist.githubusercontent.com/wwalker/5a2561dc964c153617eb1334748a9cb0/raw/b4113f7759dca447baaceda556b4bab0c375a5e9/ThePlan.md

**Comment by wwalker** [comment]
* First support:
```
Bold
Underline
InvertColors
ClearAttributes
ResetAllAttributes

Red
IntenseRed
OnRed
OnIntenseRed
```

**Comment by simov** [comment]
Got it, thanks. Seems to be working with Remark though. You can switch between two compilers/parsers available using the extension dropdown.

The default one, Marked, fails on the above snippet, at least the version that was bundled with the extension last time.

Remark, however, renders the above snippet correctly. It only fails if you enable the `pedantic` option for it.

Either way it's a compiler issue, I'll bump the Marked version on next release and see how that goes.

**Comment by simov** [comment]
Seems to be working in Markdown Viewer v5.2 for all of the supported compilers: `marked`, `remark` and `markdown-it`.
