### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by Guzim** [simov/markdown-viewer#126]
# Mermaid
Mermaid is a special syntax to draw different types of graphs.   
You can find the documentation here : [mermaid](https://mermaid-js.github.io/mermaid/#/) 

I use [mermaid](https://mermaid-js.github.io/mermaid/#/) to draw graphs and I store my .md on the cloud. 

# Markdown-viewer
I use Markdown-viewer as a Chrome extension. It permits me to see the .md files in my browser when I open such a file either localy or in the cloud. 

# Request
Is it possible to support mermaid in markdown-viewer ?   
I would love to see my graphs when I open a .md file in Chrome browser

**Comment by simov** [comment]
That would be great, I'm also using Mermaid diagrams from time to time.

**Comment by PeaceBomber** [comment]
Such a nice advice. It will be the best tool for markdown. Thanks, simov.

**Comment by simov** [comment]
Mermaid diagrams are now supported in v4.0, note that you have to wrap your diagrams in fenced code blocks:

    ```mermaid
    sequenceDiagram
    ```

or

    ```mmd
    sequenceDiagram
    ```
