### ISSUE TITLE
Why are your themes a single line?

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [simov/markdown-viewer#128]
Just a question. Why are all of your CSS theme files a single line of code? That makes them really hard to read. 

https://github.com/simov/markdown-viewer/tree/master/themes

**Comment by simov** [comment]
Themes are actually here https://github.com/simov/markdown-themes and I'm minifying them with a script. All scripts are inside the `build` folder.

**Comment by simov** [comment]
Markdown Viewer v5 got released with 30 new themes, check them out, they are really great.
