### ISSUE TITLE
Support for emoji

### ISSUE THREAD

**Issue by tcjcodes** [simov/markdown-viewer#13]
Are there any plans to add support for emoji, like GitHub?

**Comment by simov** [comment]
Interesting idea. I'll have to think about it. Thanks for the feedback!

**Comment by simov** [comment]
:wave: @tcjcodes emoji support landed in version 3.0

For now only emoji shortnames are supported, like: `:sparkles:` will result in :sparkles: 

The unicode symbols, like `✨` are not converted into images, also ascii emoji are not being converted.

Let me know what do you think.

**Comment by tcjcodes** [comment]
@simov It looks awesome - thanks so much! Loving the emoji support :smile: :sparkles: :thumbsup:

**Comment by simov** [comment]
I'm glad you like it! :sunglasses:
