### ISSUE TITLE
Dark Theme for TOC

### ISSUE THREAD

**Issue by ShobanChiddarth** [simov/markdown-viewer#132]
I use the Github Dark theme. But entire webpage is not dark
![image](https://user-images.githubusercontent.com/68191453/101459296-12cbfe80-395e-11eb-9cac-9d002a8210af.png)
Here is what I enabled 
![image](https://user-images.githubusercontent.com/68191453/101459352-22e3de00-395e-11eb-8936-4f6c414a1020.png)
and the whole page is not dark. Only the content is dark. 
![image](https://user-images.githubusercontent.com/68191453/101459386-30996380-395e-11eb-95b4-35aaf5fddce1.png)
These links to pages are not dark. Please make that also dark.

And another thing.
![image](https://user-images.githubusercontent.com/68191453/101459462-49a21480-395e-11eb-957b-fccf7c18a8f3.png)
The file is going beyond the screen. i.e. the markdown file takes some extra space than the screen. Please make it fit within the screen so that it would reduce the back and forth scrolling time. 

And, now I need everything I enabled as those help me in organising the notes. So please make that headers list also dark and that page to fit to the screen. Thanks. Please fix those.

**Comment by simov** [comment]
This got implemented in Markdown Viewer v5, you can download it from the Chrome Web Store or from the [releases](https://github.com/simov/markdown-viewer/releases) section here.
