### ISSUE TITLE
Incorrect indented list rendering

### ISSUE THREAD

**Issue by JeppeSRC** [simov/markdown-viewer#135]
Indented items in unordered lists are incorrectly rendered in firefox works fine in chrome.  I haven't tested any other browsers.

Markdown:
```
- Hello
- World
- List
-- Ident
- Opsie
```

Result:

FireFox 
![image](https://user-images.githubusercontent.com/6404138/104130314-4987a100-5370-11eb-8306-c1f3afd51dd2.png)

Chrome
![image](https://user-images.githubusercontent.com/6404138/104130327-5c01da80-5370-11eb-9674-a336ffb73bec.png)

**Comment by simov** [comment]
I see, most likely Firefox picks up some default style, because it adds 16px padding top on the nested `ul` list.

**Comment by simov** [comment]
Seems to be working in latest Markdown Viewer v5.1
