### ISSUE TITLE
Graceful hot reload

### ISSUE THREAD

**Issue by hyrious** [simov/markdown-viewer#136]
Instead of `location.reload(true)`, it may feel better to just `container.innerHTML = body`.

https://github.com/simov/markdown-viewer/blob/d7f9bfefbbddb7022b4b577e328f67a079bf11bb/content/index.js#L270-L272

**Comment by simov** [comment]
Yes, that sounds like a good idea. However currently other functionality of the extension is tied to the page load event, so it will require rethinking the entire content page code.

**Comment by simov** [comment]
This was implemented in Markdown Viewer v5, you can download it from the Chrome Web Store or from the [releases](https://github.com/simov/markdown-viewer/releases) section here.
