### ISSUE TITLE
A error in console

### ISSUE THREAD

**Issue by jerviscui** [simov/markdown-viewer#138]
The file is :
```
# 1

## AA

### 安装 JDK

* Item 1
  * Item 2
* Item 4
  * Item 5
```

The error :
![image](https://user-images.githubusercontent.com/6396748/106233294-1f1f5a00-6231-11eb-967d-1166fe856cd6.png)

**Comment by simov** [comment]
This seems to be an error thrown by MathJax when the MathJax option is enabled but there isn't anything for MathJax to render on that page. This shouldn't break the extension though.

**Comment by simov** [comment]
MathJax got updated in Markdown Viewer v5, you can download it from the Chrome Web Store or from the [releases](https://github.com/simov/markdown-viewer/releases) section here.
