### ISSUE TITLE
Layout is wrong

### ISSUE THREAD

**Issue by jerviscui** [simov/markdown-viewer#139]
The file is :
```
1. aaaaaaaaaaaaa

    ```
    make -j4
    make install
    ```

    - `-j4`，表示以 4 核心运行，可以省略

    查看安装结果：

    ```
    ls /usr/local/mysql/
    ```
```

**The right layout like this :**
![image](https://user-images.githubusercontent.com/6396748/106242156-34e94b00-6242-11eb-9855-95448a46fa4f.png)

**markdown-viewer is this :**
![image](https://user-images.githubusercontent.com/6396748/106242028-00758f00-6242-11eb-8c8e-679d94cc0391.png)

**Comment by HarryvanderBeek** [comment]
![image](https://user-images.githubusercontent.com/41471235/106320585-5ca4d700-6273-11eb-95d7-fec5dc2d8ab6.png)
I'm having a similar issue where for some reason all the code-blocks are moved 37px downwards. These codeblocks overlap the first line below them.

**Comment by simov** [comment]
@jerviscui you can try the other compiler bundled with the extension - click on the extension button and pick the Remark compiler from the popup.

@HarryvanderBeek not sure what needs fixing there. I don't have those styles injected on my end, can you elaborate?

**Comment by jerviscui** [comment]
Ok， the Remark complier has right format.

There are the differents.
![image](https://user-images.githubusercontent.com/6396748/106407048-fb992100-6475-11eb-9b35-58eefc1820dc.png)
![image](https://user-images.githubusercontent.com/6396748/106407175-5af73100-6476-11eb-9b19-11201ab93a52.png)

The above green picture is from VS Code.

I just feedback this question, perhaps can help others.

**Comment by HarryvanderBeek** [comment]
I've checked and it is because of an other extension. So forget my issue. 
(In case anybody is interested, it was this extension: [JavaScript and CSS Code Beautifier](https://chrome.google.com/webstore/detail/javascript-and-css-code-b/iiglodndmmefofehaibmaignglbpdald))

**Comment by simov** [comment]
@jerviscui yes, this is a compiler issue. It depends on which compiler the VSCode plugin that you have installed is using. If it is an open source one it will be pretty easy to verify that. Markdown Viewer is bundled with the two most popular ones, but it supports [many others](https://github.com/simov/markdown-viewer#more-compilers) if installed locally.

@HarryvanderBeek yes, my guess was that something is being ingected because I couldn't find it on my end.

**Comment by simov** [comment]
Both marked and remark got updated in Markdown Viewer v5, you can download it from the Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section here.
