### ISSUE TITLE
HTML comments show up

### ISSUE THREAD

**Issue by ronakg** [simov/markdown-viewer#14]
I use HTML comments `<!-- -->` to add comments to my markdown. These shouldn't show up in the HTML preview as those are HTML comments. They don't show up on github.com, but does show up in preview generated by markdown-viewer.

Markdown

```md
# Vim and NeoVim

## Table of Contents

<!-- vim-markdown-toc GFM -->
* [Vim](#vim)
* [NeoVim](#neovim)
    * [Building](#building)
    * [C/C++ Support](#cc-support)

<!-- vim-markdown-toc -->
```

Preview

```
Vim and NeoVim

Table of Contents

<!-- vim-markdown-toc GFM -->
- Vim
- NeoVim
    - Building
    - C/C++ Support
<!-- vim-markdown-toc -->
```

**Comment by simov** [comment]
Hi @ronakg ,

The `sanitize` option is responsible for rendering HTML tags:
![sanitize](https://cloud.githubusercontent.com/assets/1694112/23507411/a393a702-ff55-11e6-8d1e-f3e54479cd84.png)

You should *disable* this option if you want the HTML tags to be rendered. HTML comments being a special HTML tag will therefore disappear.

**Comment by ronakg** [comment]
Thanks. That works.
