### ISSUE TITLE
Metadata with Remark Compiler

### ISSUE THREAD

**Issue by fcomoreira1** [simov/markdown-viewer#142]
I know the remark compiler can interpret yaml code like for metadata
```
---
title: Index
description: This is my Index Page
tags: ['index']
---
```
It would be great to be able to use this "metadata" for things like setting up the page title and icon.

This is just a feature request, but as is your program is great!

**Comment by simov** [comment]
This was fixed in v5.1, now both YAML and TOML frontmatter blocks are being removed and if a `title` attribute exists it is being set as the title of the document. Not sure how a favicon would work, but now the extension is adding its own icon to every markdown page rendered with it.
