### ISSUE TITLE
Remarkable Compiler breaks Table Of Contents 

### ISSUE THREAD

**Issue by Expletive** [simov/markdown-viewer#145]
I'm using the compilers branch of markdown-viewer and using the remarkable compiler.  The headers don't have an id attribute, so all table of contents entries direct to href="#null". This makes the table of contents rather useless for navigating the rendered page.

![image](https://user-images.githubusercontent.com/9963278/114467151-56e63e80-9b9e-11eb-8ba8-713c9dcc39ed.png)

**Comment by simov** [comment]
Thanks for reporting it, I haven't checked that in awhile.

**Comment by simov** [comment]
Hi, I think Remarkable isn't maintained very well lately, you can try any of the supported compilers instead.
