### ISSUE TITLE
Add CSS & HTML Support

### ISSUE THREAD

**Issue by pronoymukherjeewritescode** [simov/markdown-viewer#148]
Please add HTML & CSS support as it would allow users to integrate CSS & HTML into their Markdown  files....

**Comment by JerryGreen** [comment]
It is already possible. You can put, for example:

```html
# This is my markdown file

<style>
img[align=left] {
  padding-right: 0 !important;
}
table[align=left] {
  padding-right: 20px;
}
</style>

## Subtitle

Some description, etc...

![image](...)
```

**Comment by pronoymukherjeewritescode** [comment]
That was CSS, but what about HTML?

**Comment by JerryGreen** [comment]
@pronoymukherjeewritescode don’t you see `style` tag? The same way you can you whatever else tags: div, img, video, iframe, etc

**Comment by pronoymukherjeewritescode** [comment]
![markbug](https://user-images.githubusercontent.com/79092569/124351006-82188100-dc15-11eb-9c5b-d91f292f3c25.png)

It isn't working...

**Comment by JerryGreen** [comment]
@pronoymukherjeewritescode copy entire markdown text file pls

**Comment by pronoymukherjeewritescode** [comment]
> @pronoymukherjeewritescode paste entire text/code of the file into here pls

I copied the code you gave here:

**Comment by JerryGreen** [comment]
@pronoymukherjeewritescode this is weird. Because what I see is:

![image](https://user-images.githubusercontent.com/13215662/124352974-19350700-dc1d-11eb-853e-0dae1f0c8236.png)

**Comment by pronoymukherjeewritescode** [comment]
Did you use the same code for this?

**Comment by simov** [comment]
@pronoymukherjeewritescode you have to disable the `sanitize` option.

**Comment by pronoymukherjeewritescode** [comment]
Code I used:
```
| Before | After |
| ----------- | ----------- |
| ```
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td></td>
</tr>
</tbody>
</table>
```      |   <table> <thead> <tr> <th>Before</th> <th>After</th> </tr> </thead> <tbody> <tr> <td></td> <td></td> </tr> </tbody> </table>    |
```
Output:
![marktable](https://user-images.githubusercontent.com/79092569/124356493-e5191080-dc33-11eb-88ca-f1e772facbe6.png)

Thanks @simov, it worked, now I can use HTML & CSS!!!!
