### ISSUE TITLE
Numbered lists restarts at 1 after a code block within two list items

### ISSUE THREAD

**Issue by ajkshum** [simov/markdown-viewer#15]
Example markdown:

1. item 1

```
	code block
```

2. item 2

3. item 3

Renders as:

1. item 1

```
	code block
```

1. item 2

2. item 3

See attached screenshot when viewing in Chrome.
![markdownviewer-bug](https://cloud.githubusercontent.com/assets/26149006/23523598/9913cf0a-ff55-11e6-8190-748fafe2f842.png)

**Comment by simov** [comment]
Hi @ajkshum, thanks for reporting this issue!

Unfortunately this is an issue in the [markdown parser](https://github.com/chjj/marked) that I'm using internally. There are other small inconsistencies here and there between the marked parser and the GitHub parser.

I have an idea for an option that will allow the users to choose a parser, for example the GitHub one which will require additional permissions, and will make an HTTP request to their API. This will solve the problem for users that need the exact GitHub markdown output at all times.

**Comment by simov** [comment]
Hi @ajkshum, I switched to the [Remark](https://github.com/wooorm/remark) compiler. You should receive the update automatically. It fixes this issue. You only have to navigate to the compiler tab in the extension's popup and choose the Remark compiler from the select box.
