### ISSUE TITLE
How do I enable the "Content" tab/options?

### ISSUE THREAD

**Issue by POTSandSTOP** [simov/markdown-viewer#150]
I'd like to enable TOC but when I go to the extension options, instead of this (image shamefully hijacked from #132): 

-----

![this](https://user-images.githubusercontent.com/68191453/101459352-22e3de00-395e-11eb-8936-4f6c414a1020.png)

-----

I see this:

![Chrome Legacy Window_Markdown Viewer - Google Chrome - 2021-07-27 11_29_44 AM - 2547x1367](https://user-images.githubusercontent.com/492973/127208530-0941b999-1f10-4cc2-beb5-9f8d79f34cf0.png)

**Comment by simov** [comment]
Click on the extension button with your left mouse button.

**Comment by POTSandSTOP** [comment]
>Click on the extension button with your left mouse button.

When I do that, all I get is the "Allowed Origins" as shown in my screen capture.

What would you like me to try next?

**Comment by simov** [comment]
Uhm, which browser is that?

Essentially the extension have a button like any other, and when you click on a popup shows up. Then what you are showing me is the options page instead.

So I'm not sure how this default functionality isn't working on your end. This is controlled by the browser, not the extension.

**Comment by POTSandSTOP** [comment]
>Google Chrome is up to date
>Version 92.0.4515.107 (Official Build) (64-bit)

I'm running on Windows 10.

I'll disable the extension for now and wait for the next Chrome update. Thanks for trying anyway.

**Comment by simov** [comment]
I'm using `Version 92.0.4515.107 (Official Build) (64-bit)` on Linux and it works.

**Comment by POTSandSTOP** [comment]
I don't know how to proceed if it's a browser issue yet we're both on the same version of Chrome other than the OS (Windows 10 vs. Linux). I don't know what to do other than waiting to see if the next Windows 10 Chrome update works for me. Thanks again though for trying to help.

**Comment by asplingzhang** [comment]
I have then same problem when planning to enable toc. same as UNIVAC-Colonel-Panic

**Comment by asplingzhang** [comment]
I have then same problem when planning to enable toc. same as @UNIVAC-Colonel-Panic
