### ISSUE TITLE
 bug report

### ISSUE THREAD

**Issue by InvisibleLeVen** [simov/markdown-viewer#153]
The local md file cannot be viewed, I set it up according to the tutorial
![image](https://user-images.githubusercontent.com/24772156/132638626-1d5dae33-ef3d-4081-a972-2bcee6f46bf2.png)
No matter how I refresh it, the md file still cannot be parsed
![image](https://user-images.githubusercontent.com/24772156/132638821-dfdc7933-2f1e-4f35-80b3-214ef0fd3596.png)

**Comment by simov** [comment]
Can you try with lowercased file extension, like `md` instead of `MD`?

**Comment by InvisibleLeVen** [comment]
> Can you try with lowercased file extension, like `md` instead of `MD`?

I tried to change the file suffix to md, it can be parsed correctly, I suggest to support the uppercase

**Comment by simov** [comment]
Yes, that's a known issue, in the meantime you can update the Path Matching RegExp. Go to the options screen for the Markdown Viewer extension, you can click on the `Advanced Options` button inside the extension's popup. Then for the `file://` entry add `MD` something like `...|md|MD|..`
