### ISSUE TITLE
enable toc failed

### ISSUE THREAD

**Issue by asplingzhang** [simov/markdown-viewer#154]
I have then same problem when planning to enable toc. same as @UNIVAC-Colonel-Panic

_Originally posted by @asplingzhang in https://github.com/simov/markdown-viewer/issues/150#issuecomment-926492007_

**Comment by simov** [comment]
It's a very strange issue, I can't think of any rational reason to not have that default functionality working.

**Comment by asplingzhang** [comment]
![image](https://user-images.githubusercontent.com/91318187/134674779-cc660640-1e44-4722-83ed-b858da8308bb.png)
 when I install markdown-viewer manually with branch compilers,errors showed above in the extension view. is this helpful ?

**Comment by simov** [comment]
Does this happen with `master` branch as well? Compilers branch seems to be a bit behind so I might have to check that out.

**Comment by asplingzhang** [comment]
yes,same issue with master branch.

**Comment by asplingzhang** [comment]
Here is the info of running environment:
version of google chome:94.0.4606.61(x86_64)
os version:macOS Big Sur 11.6

**Comment by asplingzhang** [comment]
TOC feature  really matters to ones who use markdown-viewer.

**Comment by simov** [comment]
That's very weird. There is another way to get to the popup by navigating to:

```
chrome-extension://hlhekimkdlfgclhbfjdhhhompbbhbnoc/popup/index.html
```

Just make sure the extension ID is correct, you can see it on the Manage Extensions page `chrome://extensions/`

**Comment by asplingzhang** [comment]
Thanks a lot! It works,WOW,:) Amazing~
