### ISSUE TITLE
Mermaid Scripts not work

### ISSUE THREAD

**Issue by yiwc** [simov/markdown-viewer#156]
Dear simov, 

THanks for your great work. This mermaid feature looks can not work, may you have a look?

```mermaid
%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ff0000'}}}%%
        graph TD
          A[Christmas] -->|Get money| B(Go shopping)
          B --> C{Let me think}
          B --> G[/Another/]
          C ==>|One| D[Laptop]
          C -->|Two| E[iPhone]
          C -->|Three| F[fa:fa-car Car]
          subgraph section
            C
            D
            E
            F
            G
          end
```

**Comment by yiwc** [comment]
Hi THanks for your reply. Here the inline javascript looks can not work

**Comment by feckertson** [comment]
The [theming capability](https://mermaid-js.github.io/mermaid/#/theming) does not seem to work prior to mermaid 8.9.1 and markdown-viewer pulls in version 8.8.4.  I would think markdown-viewer should just pull in the latest mermaid release, but PR #159 will also address this concern.
