### ISSUE TITLE
Please add support for <div class='mermaid'>

### ISSUE THREAD

**Issue by mcdon-ron** [simov/markdown-viewer#157]
The `<div class='mermaid'>` is the default usage listed on [Mermaid's site](https://mermaid-js.github.io/). It'd also be useful for scenarios where you have to add html within markdown, something like putting some mermaid graphs in an html table.

Thank you

**Comment by simov** [comment]
This is supported in v5.1, have a look at the updated documentation https://github.com/simov/markdown-viewer#mermaid Also note that your HTML tags have to be structured exactly as shown in the code example, so make sure you copy/paste that exactly as it is.
