### ISSUE TITLE
Mermaid state diagram rendered incorrectly

### ISSUE THREAD

**Issue by EuropeanDeveloper** [simov/markdown-viewer#160]
According to [mermaid webpage](https://mermaid-js.github.io/mermaid/#/stateDiagram?id=setting-the-direction-of-the-diagram) it should be possible to define direction for a state diagram.

However, it looks like the direction statement is not supported in Markdown Viewer 4.0 and thus the diagram is rendered incorrectly:

![picture](https://user-images.githubusercontent.com/52759436/145570071-fbdf3166-2e93-4868-8b4e-38e5477349d2.png)

_Browser_: Mozilla Firefox 95.0

**Comment by simov** [comment]
Can you provide a sample mermaid code snippet? Probably I need to update the library version.

**Comment by EuropeanDeveloper** [comment]
It's the same one mentioned in [mermaid webpage](https://mermaid-js.github.io/mermaid/#/stateDiagram?id=setting-the-direction-of-the-diagram):

```
```mermaid
stateDiagram
    direction LR
    [*] --> A
    A --> B
    B --> C
    state B {
      direction LR
      a --> b
    }
    B --> D
\```
```

**Comment by xayjin** [comment]
Similar issue, solved after changing mermaid.min.js to newest.

**Comment by simov** [comment]
Ok, then that means I need to update it too :+1:

**Comment by wow-yes** [comment]
Hello, same issue here. Thanks.

**Comment by simov** [comment]
Mermaid got updated in Markdown Viewer v5, you can download it from the Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section here.
