### ISSUE TITLE
Code blocks should have the same background, font size and type

### ISSUE THREAD

**Issue by EuropeanDeveloper** [simov/markdown-viewer#162]
Code blocks without defined language should have the same background, font size and font type as code blocks for the rest of languages. It is more uniform and looks better in markdowns with codes in multiple languages.

For example:
```
\```
  Something
\```

\```text
  Something
\```

\```batch
  rem Something
\```

\```html
  <!-- Something -->
\```
```

is rendered in Markdown Viewer 4.0 with `GITHUB` theme like this:

![picture1](https://user-images.githubusercontent.com/52759436/145625884-15495b72-18cb-43b6-802a-11ea9c2092d4.png)

The same code formatted by GitHub:

![picture2](https://user-images.githubusercontent.com/52759436/145626259-f94c6584-2c0e-4e5c-add2-cd9535c8a5ad.png)

_Browser_: Mozilla Firefox 95.0

**Comment by simov** [comment]
Again that's styled by Prism.js, but thanks for the feedback.

**Comment by simov** [comment]
That was fixed in Markdown Viewer v5, however, the Firefox release will come up later this year once they implement the support for Service Workers in manifest v3, so stay tuned for that.
