### ISSUE TITLE
Inline code and code blocks should have the same background

### ISSUE THREAD

**Issue by EuropeanDeveloper** [simov/markdown-viewer#163]
Inline code and code blocks should have the same background. It is more uniform and looks better in markdowns that contains both variants.

For example:
```
`git config --global user.name "Sam Smith"`

```batch
git config --global user.name "Sam Smith"
\```
```

is rendered in Markdown Viewer 4.0 with `GITHUB` theme like this:

![picture1](https://user-images.githubusercontent.com/52759436/145627696-f9514c47-4f69-4e49-808a-a95353c0b6bd.png)

The same code formatted by GitHub:

![picture2](https://user-images.githubusercontent.com/52759436/145627785-5e43d864-3038-47c3-bce2-ee0e709cab30.png)

_Browser_: Mozilla Firefox 95.0

**Comment by simov** [comment]
I see, this is because the code blocks are being rendered using Prism.js

**Comment by simov** [comment]
This was fixed in Markdown Viewer v5, you can download it from the Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section here.
