### ISSUE TITLE
Emojis in headings

### ISSUE THREAD

**Issue by Hashemian01** [simov/markdown-viewer#164]
Somehow markdown viewer stopped compiling emojis in headings and some other parts (bold texts for example). Normal texts are still fine. Also I have no problem when using shortcode emojis.

![image](https://user-images.githubusercontent.com/48093461/146642708-e61cb4c0-7fb1-4f19-abaf-73446f4701ab.png)

**Comment by simov** [comment]
Is this a remote page? Maybe they have enabled string Content Security Policy. If that's the case you can try to disable it for that origin through the Advanced Options menu.

**Comment by Hashemian01** [comment]
No, it's a local file. So I figured that in Radar, Foghorn, Markdown and Markdown5 themes, the heading problem doesn't exist but the problem with the bold texts persists. Might have something to do with the fonts.

**Comment by simov** [comment]
Not sure how emojis are related to that, can you add a markdown snippet here that I can use to reproduce this one my end?

**Comment by Hashemian01** [comment]
Here is the snippet
~~~ markdown
# ⭐🙏🔰 :star: :pray: :beginner: H1 test

## ⭐🙏🔰 :star: :pray: :beginner: H2 test

### ⭐🙏🔰 :star: :pray: :beginner: H3 test
Text test ⭐🙏🔰 :star: :pray: :beginner:
**Bold text test ⭐🙏🔰 :star: :pray: :beginner:**
~~~

Output for the Github theme
![image](https://user-images.githubusercontent.com/48093461/146658817-dc65bb09-cd76-4e6b-adce-0ae93d98080c.png)

Output for the Radar theme
![image](https://user-images.githubusercontent.com/48093461/146658846-0f0a4952-b6d1-43b3-b09f-ffec2615d2ec.png)

**Comment by simov** [comment]
Hi, on my end changing the theme does not affect the rendering of the icons. I get colored icons in all cases. So I'm thinking that the way the Unicode character (emoji) is being rendered is dependent on your Operating System. In case there is an update in your OS that breaks it, this may explain why it stopped working for you.

**Comment by Hashemian01** [comment]
Apparently, this is known bug in chrome 96 as reported [Here](https://dev.to/inhuofficial/chrome-changed-emojis-in-headings-a-workaround-if-you-want-normal-emojis-again-4n4o) and [Here](https://bugs.chromium.org/p/chromium/issues/detail?id=1266022) and has nothing to do with the extension. Therefore, I closed the issue.
