### ISSUE TITLE
If the table contains inline-coded `|`, it will be broken

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [simov/markdown-viewer#165]
# If the table contains inline-coded `|`, it will be broken

When creating table containing inline-coded vertical bar, the table is broken.

> demo

```markdown
|                contents                | description       |
| :------------------------------------: | :---------------- |
| If the table contains inline-coded `|` | it will be broken |
```

> Result of displaying

![tabel-in-inlineCoeded-verticalBar](https://user-images.githubusercontent.com/75878492/147399374-9d2d7a44-cab5-4c18-86af-af4b6cd45b62.png)

This problem occurs in both `Remark` and `Marked` compilers.
Of course, this problem doesn't seem to depend on the CSS theme.

## Version info.

| Microsoft Edge  | 96.0.1054.62 (64bit) |
| :-------------: | :------------------- |
| Markdown Viewer | 4.0                  |

Thank you for the very easy-to-use extension!

**Comment by simov** [comment]
Yes, that seems to be a compiler issue.

**Comment by Yarakashi-Kikohshi** [comment]
Should this issue be raised by [`remark.js`](https://github.com/remarkjs/remark) or [`marked.js`](https://github.com/markedjs/marked)?
If so, I will close this issue.

**Comment by simov** [comment]
Yes, it is part of what the compiler/parser does. They may have a fix for it already, in that case I will have to update the version used here.

**Comment by Yarakashi-Kikohshi** [comment]
Thank you for your prompt reply!!:smile:

And, I checked the issue of each repository.
Similar issues were discussed in each compiler's repository, but I couldn't find the conclusion I expected.

I'm going to put up with it until the problem is resolved.:persevere:

## Current status regarding this issue

### marked\.js

In `marked.js`, it seems to be stuck due to regex problems.

> *cf.* [The vertical bars within backsticks shouldn't be interpreted as table cell delimiter. · Issue #1375 · markedjs/marked](https://github.com/markedjs/marked/issues/1375)

### remark\.js

In `remark.js`, inline-coded `|` is interpreted as a table, which is the same behavior as GFM, so it does not seem to correspond at present.

> *cf.* [Fix inline code and vertical bars in tables by wooorm · Pull Request #420 · remarkjs/remark](https://github.com/remarkjs/remark/pull/420)

**Comment by wooorm** [comment]
The displayed result matches how GH does it btw, try pasting it here:

|                contents                | description       |
| :------------------------------------: | :---------------- |
| If the table contains inline-coded `|` | it will be broken |

**Comment by Yarakashi-Kikohshi** [comment]
@wooorm 
Yes. I found out by looking at issue # 420 of `remark.js`.

I think it's important to look similar to GH, but I don't want `` `|` `` to be considered part of the table.
It seems that `mark.js` will support the notation I am expecting, so I wait until then...:persevere:
