### ISSUE TITLE
custom id support??

### ISSUE THREAD

**Issue by wow-yes** [simov/markdown-viewer#168]
[Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html)

> the following headings will all be assigned the identifier `foo`:
> 
>     # My heading {#foo}
>     
>     ## My heading ##    {#foo}
>     
>     My other heading   {#foo}
>     ---------------
> 
> (This syntax is compatible with [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/).)

Will this plugin support this feature? Thanks.

For now, I use  `######` as an alternative 。

**Comment by simov** [comment]
I think the underlying parsers that this extensions use may have a plugin for that. I will have to check.

**Comment by simov** [comment]
Markdown Viewer v5.2 got released with a new default compiler called markdown-it and an option called `attr` that addresses this issue https://github.com/simov/markdown-viewer#compiler-options
