### ISSUE TITLE
Support for Task lists

### ISSUE THREAD

**Issue by s0h3ck** [simov/markdown-viewer#17]
Are there any plans to add support for task lists, like GitHub?

Example: https://github.com/blog/1825-task-lists-in-all-markdown-documents

**Comment by simov** [comment]
Thanks for the feedback @s0h3ck. I'm going to research about other markdown parsers and eventually let the user to choose one in the extension.

Currently I'm using the [marked](https://github.com/chjj/marked) parser/compiler internally. There are other small inconsistencies between what you can see on GitHub and what the marked parser is capable of.

**Comment by s0h3ck** [comment]
Interesting :)

I think markdown-it might be more suitable for your needs, easier than showdownjs to implement plus has the emoji feature (it will solve the issue #13), but they do not support task lists. Maybe we can ask them to add the feature.

In addition, showndownjs might be an interesting choice.
The link: https://github.com/showdownjs/showdown

As well, for the emoji issue, you could use showdown-emoji.
Here is the link : https://www.npmjs.com/package/showdown-emoji

Happy coding :)

**Comment by zhiqiexing** [comment]
Hello, I hope this extension can support task list

**Comment by simov** [comment]
Thanks for the suggestions @s0h3ck it was very helpful!

I just published version 2.8 where you can choose between the [marked](https://github.com/chjj/marked) and [showdown](https://github.com/showdownjs/showdown) compilers. All available compiler options can be found [here](https://github.com/simov/markdown-viewer#compiler-options), also if you hover over any of the options in the extension's popup, a tooltip will appear after a second or two.

Here is how it currently looks like: ![tasklists](http://i.imgur.com/XfvOqYd.png)

In fact there is a [PR](https://github.com/chjj/marked/pull/587) in the Marked issue tracker that adds support for tasklist probably long before Showdown, but the Marked maintainers seems to be somewhat hesitant about adding more GFM features for some reason.

So I thought that it's better to have both parsers. The current implementation and UI allows me to add more parsers if there is a need to.

As usual let me know if you find any bugs or missing features. The only one I found so far missing in Showdown is [this](https://github.com/showdownjs/showdown/issues/366) but there could be many.

**Comment by s0h3ck** [comment]
Nice work :)

I noticed a bug with nested element, but ShowdownJS Team is already aware of it [here](https://github.com/showdownjs/showdown/issues/357).

**Comment by simov** [comment]
Yep, I'll try to help out there with what I can.

I think marked and showdown are the two most prominent parsers for Javascript at the moment.

Here is the full list out of my research:

- https://github.com/chjj/marked
- https://github.com/showdownjs/showdown
- https://github.com/markdown-it/markdown-it
- https://github.com/jonschlinkert/remarkable
- https://github.com/evilstreak/markdown-js
- https://github.com/jgm/commonmark.js

**Comment by simov** [comment]
Same issue here: https://github.com/showdownjs/showdown/issues/367#issuecomment-290514385

I'm actually compiling a list of all bugs that I've found. It's not that bad but there a couple of things missing.

**Comment by simov** [comment]
Another quick release, I dropped Showdown in favor of [Remark](https://github.com/wooorm/remark), you should receive the update automatically.

Remark covers all my [syntax test cases](https://raw.githubusercontent.com/simov/markdown-viewer/master/syntax.md), you have to add the `raw.githubusercontent.com` origin to enable the extension for that URL. Then you can compare it to how GitHub [renders is](https://github.com/simov/markdown-viewer/blob/master/syntax.md).

Remark also have huge [ecosystem of plugins](https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins) so adding things like emoticons and other features won't be a problem.

**Comment by jr-grenoble** [comment]
Prelim: this markdown viewer is a *great*  Chrome extension!

I bumped into this thread while trying to remove bullet marks from task lists (they are redundant) and enabling the corresponding input checkboxes. I don't think this is doable without a change to the Chrome extension, unless javascript scripts are processed by the viewer.

In @simov latest answer, the following links are dead: [syntax test cases](https://raw.githubusercontent.com/simov/markdown-viewer/master/syntax.md)
and [rendering](https://github.com/simov/markdown-viewer/blob/master/syntax.md).

> Another quick release, I dropped Showdown in favor of [Remark](https://github.com/wooorm/remark), you should receive the update automatically.
> 
> Remark covers all my [syntax test cases](https://raw.githubusercontent.com/simov/markdown-viewer/master/syntax.md), you have to add the `raw.githubusercontent.com` origin to enable the extension for that URL. Then you can compare it to how GitHub [renders is](https://github.com/simov/markdown-viewer/blob/master/syntax.md).
> 
> Remark also have huge [ecosystem of plugins](https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins) so adding things like emoticons and other features won't be a problem.

**Comment by simov** [comment]
The examples were extracted into separate repo: https://github.com/simov/markdown-syntax

I don't see a problem with the rendering of task lists.

**Comment by jr-grenoble** [comment]
Thanks for the quick response; indeed, bullet marks are no longer present in task lists.

However, checkboxes are "disabled" by default. Of course, this makes sense as there's no engine to process them. However, from a pure visual standpoint, the check marks can be useful: e.g. for someone using markdown to set up a checklist and then print the result after manually checking it (this is my actual use case).

Is there anyway to make them enabled ?

ps: I tried to inject CSS style in my md file (input:checked { background: red; color: white; }) but this is to no avail.
