### ISSUE TITLE
How are unbreakable spaces interpreted? [Question]

### ISSUE THREAD

**Issue by Uhter** [simov/markdown-viewer#170]
Hi,

I don't understand how are unbreakable spaces interpreted?

I use [ghostwriter](https://github.com/wereturtle/ghostwriter) to create markdown files. If I write : 

```
There are one unbreakable space before colon : done  
There are fifteen before colon               : done
```

Colons are vertically aligned in the code AND in the ghostviewer preview. That's what I want and I use unbreakable spaces for that.
But markdown-viewer shows this with any theme : 

> There are one unbreakable space before colon : done
> There are fifteen before colon               : done

What's the reason why please?

**Comment by simov** [comment]
Probably I don't understand the questions but in general only fenced code blocks and probably inline code blocks should preserve regular empty spaces.

**Comment by Uhter** [comment]
Hello @simov

That's right, and I think ghostwriter do that in a different way than the others editors. This was the reason why I didn't understand.
So, it's not markdown-viewer's fault.

Thanks for your help ;)
