### ISSUE TITLE
How to include a mermaid chart containing href tag in markdown

### ISSUE THREAD

**Issue by Andone02** [simov/markdown-viewer#173]
Hi, thanks to this extension, I can create a chart using mermaid. The next step is to make a chart contain links to navigate to different urls. Right now, it looks like this

![Problem](https://user-images.githubusercontent.com/93755071/155054721-0fcc7949-1842-40b5-8769-ea7b5c8770df.PNG)

The corresponding code is this
![Code](https://user-images.githubusercontent.com/93755071/155055915-12097e92-0260-4c5f-8a01-402bb9777187.PNG)

It seems easy but just got stuck in this. Any ideas to help me out?

**Comment by simov** [comment]
Not sure tbh, I was able to reproduce it:

```mmd
graph TD
  A[This is an important <a href='https://google.com'>click me</a>]
```

**Comment by Andone02** [comment]
Maybe more detailed info. Those lines are in a local markdown file and chrome with this extension is used to open it. I can't add link in mermaid graph. If in mermaid itself, it works. I don't know whether this will make any difference to you.

**Comment by Andone02** [comment]
Find something here.
https://mermaid-js.github.io/mermaid/#/usage?id=enabling-click-event-and-tags-in-nodes
![mermaid](https://user-images.githubusercontent.com/93755071/155151240-32095a0d-e732-4dc1-9f2a-295af5a5d89f.PNG)

Could I customize this security level to loose or select the version of mermaid in this extension?

**Comment by simov** [comment]
Sure, pull this repository and search for `mermaid` here: https://github.com/simov/markdown-viewer/blob/master/content/index.js

**Comment by simov** [comment]
Mermaid got updated in the latest Markdown Viewer v5, you can download it from the Chrome Web Store or from the [releases](https://github.com/simov/markdown-viewer/releases) section here.
