### ISSUE TITLE
Violated github-flavoured-markdown footnotes rules for displaying

### ISSUE THREAD

**Issue by jerrygreen** [simov/markdown-viewer#174]
What the extension does emit:

![image](https://user-images.githubusercontent.com/13215662/155844507-25fe0169-f998-4673-9496-a130e5ccf860.png)

Actual footnotes in github flavored markdown[^1][^2]:

![image](https://user-images.githubusercontent.com/13215662/155844416-11f1fd49-f991-4e01-af3e-a1711682dce4.png)

The extension violates these rules:

1. Square brackets `[` and `]`, near the link to a footnote, should be emitted. It looks more recognizable and easier to click.
2. Text ids `[^note]` should translate into a number. That is common for footnotes (ever seen the else case, say, on wiki?).
3. There should be a humble `↩` text symbol. Not an ugly "↩" emoji.
4. Footnotes should be smaller than normal text, and grayed out.

Last but not least:

5. github-flavoured-markdown has an accurate 1px of line separator for footnotes. Not some default browser's 4px[^3].

Just in case, my compiler options (gfm enabled):

![image](https://user-images.githubusercontent.com/13215662/155844695-4165ee58-9951-4298-bf5b-c963c7b9824a.png)

P.S. I know this might be related to how "remark" package library renders, not to the extension. But I can't be sure where's the problem, gotta file it somewhere.

[^1]: [Basic writing and formatting syntax - GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes)
[^2]: [Footnotes now supported in Markdown fields - GitHub Changelog](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)
[^3]: Technically, Github, too, has some default 4px line for `hr` tag, but they don't use it, and instead they use `border-top: 1px solid var(--color-border-default)` css property, - for footnotes, and literally everywhere in their UI. Honestly I think they should change `hr` to an accurate 1px, too, - but that is less related to the issue.

**Comment by simov** [comment]
Seems like all of your concerns got fixed in the latest Remark version. Make sure you have the latest Markdown Viewer v5 that got released a few days ago. It is available on the Chrome Web Store and here in the [releases](https://github.com/simov/markdown-viewer/releases) section.
