### ISSUE TITLE
Support for loading tex extension

### ISSUE THREAD

**Issue by Mrxixixixi** [simov/markdown-viewer#175]
It seems that markdown-viewer dosen' t  support for loading some tex extension such as `physics` and ` braket`. For example, when I add `\(\require{braket}\)` in the markdown file,  the formula `$\bra{a}$` can not be compiled.

**Comment by simov** [comment]
Markdown Viewer v5.1 was migrated to MathJax v3.x and it supports all of the tex/latex extensions for it. Have a look at the updated [examples](https://github.com/simov/markdown-viewer#syntax-examples) for MathJax, there is a section at the bottom showcasing some of the tex/latex extensions that I used to test this.
