### ISSUE TITLE
mermaid - gitGraph is not rendering

### ISSUE THREAD

**Issue by dhilmathy** [simov/markdown-viewer#180]
Mermaid dragram of type `gitGraph` is not rendering.

## Sample
![image](https://user-images.githubusercontent.com/15025473/174500270-e06a8a56-731a-43d7-865c-2e744eb9e0c8.png)

## Browser used
* Microsoft Edge (*Version 102.0.1245.44*)

## Extension version
[Version 4.0](https://microsoftedge.microsoft.com/addons/detail/markdown-viewer/cgfmehpekedojlmjepoimbfcafopimdg)

## Output
* Blank code section display in browser

## Extension settings
![image](https://user-images.githubusercontent.com/15025473/174500246-c48a82a2-038f-4c21-8ee0-2e3366370d2a.png)

**Comment by ronaldpetty** [comment]
Confirming it is not rendering in Chrome. Also, if you visit GitHub in Chrome and plugin is enabled and mermaid is used the entire page breaks; sometimes nothing is rendered.

**Comment by simov** [comment]
Maybe the Mermaid version used here is outdated. 

When having the extension enabled for all remote origins you have to [exclude the github.com origin explicitly](https://github.com/simov/markdown-viewer#exclude-origin) because otherwise the extension will interfere with the page as you have observed.

**Comment by simov** [comment]
Mermaid got updated in Markdown Viewer v5, you can download it from the Chrome Web Store or from the [releases](https://github.com/simov/markdown-viewer/releases) section here. The official Edge release will come in the upcoming few weeks so stay tuned for that.
