### ISSUE TITLE
Cannot render multiple documents in Firefox

### ISSUE THREAD

**Issue by WangNianyi2001** [simov/markdown-viewer#181]
## Problem Description
After installed on Firefox, when a Markdown document is already opened & rendered with this extension, opening another Markdown document will result in a blank page.

## Reproduction
1. Start a new Firefox window.
2. Open a random Markdown document `A.md` in Firefox, and it is rendered as expected.
3. Open a different random Markdown document `B.md`, a blank page appears.
4. If you check the inspector panel, there's nothing but an empty body.
5. Close `A.md` and refresh the `B.md` page, the latter one got rendered.
6. Open `A.md` again, and it's a blank page.

## Misc Detail
- Firefox version: `101.0.1 (64-bit)`
- My documents are stored in a portable hard drive and that's probably the problem.
- MathJax is enabled.
- Just as I'm editing this post, with only a Markdown document page & this issue editing page open, refreshing the document page once results in a blank page, refreshing again and it then rendered correctly.

**Comment by simov** [comment]
I cannot reproduce this on my end. Can you try with latest Markdown Viewer v5.1 there are a lot of fixes and improvements in that release so maybe this got fixed too.

**Comment by WangNianyi2001** [comment]
@simov Thanks for replying! Somehow the problem really went away, I don't know how either.
