### ISSUE TITLE
Update mermaid version

### ISSUE THREAD

**Issue by nico-castell** [simov/markdown-viewer#189]
The version of mermaid currently used by this extension is 8.8.4. While the latest version of mermaid is [9.2.2](https://github.com/mermaid-js/mermaid/releases/tag/v9.2.2).

As a result of being out of date, some mermaid charts don't render despite having valid syntax for the newer versions.

**Comment by simov** [comment]
It will be very soon. I will let you know

**Comment by simov** [comment]
Mermaid got updated in Markdown Viewer v5, you can download it from the Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section.
