### ISSUE TITLE
Markdown viewer doesn't work -- shows raw markdown

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [simov/markdown-viewer#191]
Hello,

I find my Chrome doesn't render Markdown anymore but shows me the raw Markdown source.  This just started happening. 

Screenshot:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/66701226/206261102-140fc041-ade0-46dc-a2be-a76c29d24050.png">

This is a great extension, I've come to rely on it.  Thank you.  :)

**Comment by atsalolikhin-spokeo** [comment]
I had to go into the extension settings and allow access to `file://` URLs. Which is odd, because I hadn't changed that setting.  Something changed it for me.

**Comment by simov** [comment]
Hi, I released a major update yesterday, required for every chrome,but I managed to add some cool new features as well. I'm glad that it worked out for you.
