### ISSUE TITLE
Grey text (instead of black) after recent update (to 5.0)

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [simov/markdown-viewer#192]
Hello,

My workflow is to write my standup report in Markdown, view it in Chrome using Markdown Viewer, and select-all and paste it into Gmail, so I can send it with bullet points and links rendered by Markdown Viewer.

Since updating to 5.0 of Markdown Viewer, the text looks grey in Gmail, whereas before it was normal (black).

Is that a new setting?  Is it possible to configure Markdown Viewer to restore the old behavior?  I find the grey text on white background hard to read, whereas the black on white was fine.

Thanks for a great and very useful extension!

Aleksey

**Comment by simov** [comment]
Which theme are you using? My best bet right now is that now themes are providing some style information that the browser is able to pick up on copy to clipboard and then put it into the Gmail app, and before that it was not doing it.

**Comment by atsalolikhin-spokeo** [comment]
Yeah.  I never picked a theme... it's defaulting to GitHub and Auto.  

Wow!  There are a lot of themes.

**Comment by simov** [comment]
Yes, Markdown Viewer v5 shipped with a lot of new themes, and all of them are looking great. 

I also copy/pasted a Markdown document into the Gmail's compose textbox and the text color is definitely not true black, it is `#24292f` instead but that is picked from the default GitHub theme. I cannot remember if the text color was true black before or not, but if you take a look at a rendered readme file on github.com today it is definitely using the `#24292f` as well.

**Comment by atsalolikhin-spokeo** [comment]
Yes, I understand.  Well done on all the improvements!

If I open a "hello world" type HTML file in Chrome, the text is rendered in black.

I mean something like

```<h1>Hello world</h1>
hello hello hello```

Is there any way to get that behavior with Markdown Viewer?  :)

**Comment by simov** [comment]
That all depends on the CSS styles. By default browsers set the text color to be black `#000000` on white `#ffffff` background. Then you have CSS styles applied on top, such as the themes found in Markdown Viewer. Seems like the `Semantic` theme, that's how the theme is called, has pretty similar styling to the GitHub one and it also uses a true black color for the text.
