### ISSUE TITLE
Help page doesn't explain how to choose a theme

### ISSUE THREAD

**Issue by hubwriter** [simov/markdown-viewer#195]
My markdown pages used to render with a white background but are now rendering with a black background. I want to go back to the white background.

The readme help page (https://github.com/simov/markdown-viewer) mentions that there are "30+ themes" and contains a "Themes" section (https://github.com/simov/markdown-viewer#themes) with details of width options for themes. But it doesn't tell you how you can see which themes are available and how to choose one.

The actual settings for the extension only contain one option "Light Extension Icon for Dark Browser Theme."

Could you add information on how to choose themes so that I can get back to rendered pages looking like they did a few weeks ago (I'm guessing there was an upgrade that changed things). Thanks.

**Comment by simov** [comment]
It's the first tab inside the extension's popup, it says `Themes`. Click on it and then pick a theme from the select box. Let me know if that helps.
