### ISSUE TITLE
不能查看文件，点击文件变成直接下载该文件

### ISSUE THREAD

**Issue by bkbbbb** [simov/markdown-viewer#196]
使用该插件为什么直接是下载该文件啊，不是之前的查看了

**Comment by simov** [comment]
Excuse me, I do not understand that language. But I used Google Translate, so here is my answer: the mime type association is controlled by your operating system, not by the extension. Probably you have installed a new software recently that changed the file association for the markdown mime type and now the browser is no longer able to serve those files and instead is asking you to download them.

**Comment by bkbbbb** [comment]
So how can I solve this problem, but I don't know which newly downloaded software caused this problem. Thank you

**Comment by bkbbbb** [comment]
> 对不起，我不懂那种语言。但我使用了谷歌翻译，所以这是我的答案：mime 类型关联由您的操作系统控制，而不是由扩展名控制。可能你最近安装了一个新软件，它改变了 markdown mime 类型的文件关联，现在浏览器不再能够提供这些文件，而是要求你下载它们。

So how can I solve this problem, but I don't know which newly downloaded software caused this problem. Thank you
