### ISSUE TITLE
markdown-viewer extension blocks GitHub markdown rendering

### ISSUE THREAD

**Issue by higs4281** [simov/markdown-viewer#197]
My laptop is employer-managed, which could be playing a role, but in case others have seen this, I'm passing it along.

After installing the Markdown Viewer in a Chrome browser, I noticed some GitHub markdown pages stopped rendering. 
This is intermittent, and error signature is either a blank screen, or a flash of the content and then a blank screen.  

The devtools console shows this error:

```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at mount (index.js:140:11)
    at index.js:220:3
```
If I turn off Markdown Viewer, the page renders.

#### browser/system details
Chrome version: 108.0.5359.124 (Official Build) (x86_64)
Markdown Viewer chrome extension version: 5.0
OS: macOS Monterey 12.6
device: employer-managed macbook pro (Chrome updates are managed; some settings locked down)

**Comment by simov** [comment]
The only way Markdown Viewer can interfere with pages on GitHub is if you have allowed it on the github.com origin or most likely you have allowed access to all origins. You can read about the Path Matching Priority [here](https://github.com/simov/markdown-viewer#path-matching-priority). Also, note that allowing the extension to work on all origins is not recommended, even though there is a button to do it inside the advanced options page, it is always better to allow only the origins that you want Markdown Viewer to have access to.

**Comment by higs4281** [comment]
Thank you for the explanation, and sorry for the churn.
