### ISSUE TITLE
No Support for UTF8 Letters

### ISSUE THREAD

**Issue by janstuemmel** [simov/markdown-viewer#2]
Letters like ä,ü,ö,ß are not displayed

**Comment by simov** [comment]
I'm not able to reproduce it. I'm putting 

> Letters like ä,ü,ö,ß are not displayed

in a markdown file and then I'm seeing that symbols when rendered inside the browser.

Are you sure you saved your files using UTF8? My editor is set to UTF8 by default.

**Comment by janstuemmel** [comment]
yes, mine is set to utf8 too, i'll check out and tell you

**Comment by simov** [comment]
Let me know if you have any other issues.
