### ISSUE TITLE
unformatted Maxwell's Equations

### ISSUE THREAD

**Issue by PaltryProgrammer** [simov/markdown-viewer#200]
Please see attached PNG displaying unformatted Maxwell's equations . Please note site is raw as advised . Thank You Kindly
![unformatted Maxwell](https://user-images.githubusercontent.com/48535920/211280579-65b3afc6-22c5-4610-95c9-44d25a6188de.png)

**Comment by simov** [comment]
Click on the extension button (the little 'm'), select the 'Content' tab, and enable 'mathjax'. Here is the list of all [content options](https://github.com/simov/markdown-viewer#content-options) available and their default values.
