### ISSUE TITLE
Running into manifest issues with version 5.0

### ISSUE THREAD

**Issue by pbreheny** [simov/markdown-viewer#201]
First of all, I've used Markdown Viewer for years; it's wonderful and thank you for creating it.

However, as of Version 5.0, Chrome can no longer load any of the themes. If I go to any `.md` file on the web, Markdown Viewer recognizes it and compiles the markdown to html, but none of the CSS themes load. If I right-click and "Inspect" with Chrome DevTools, the Console shows a host of errors, all of the form:

```
Denying load of chrome-extension://ckkdlimhmcjmikdlpkmbgfkaikojcbjk/themes/github-dark.css.
Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
```

If I open a local `.md` file, the same thing happens -- unable to access any of the `.css` files -- but a different error shows up in DevTools:

```
chrome-extension://ckkdlimhmcjmikdlpkmbgfkaikojcbjk/themes/github-dark.css
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

I've tried turning off all other extensions, tried turning on and off Markdown Viewer, tried removing and re-installing the extension, but nothing seems to work. Not sure if there's anything else I can try, but wanted to raise the issue.

**Comment by simov** [comment]
Can you share your exact browser version and also operating system? This is really strange because the themes are indeed listed as [web accessible resources](https://github.com/simov/markdown-viewer/blob/main/manifest.chrome.json#L41) and that has been thoroughly tested as you can imagine.

**Comment by pbreheny** [comment]
Chrome: Version 103.0.5060.114 (Official Build) (64-bit)
Operating system: Ubuntu 20.04.5 LTS

As a side note, I did try this on another machine (Ubuntu 22), and everything worked fine, so it's definitely something specific with this machine/browser. Hmm.

**Comment by pbreheny** [comment]
Actually, just noticed that there was something blocking a Chrome update. After updating to 
Version 108.0.5359.124, this issue is resolved. :tada:

**Comment by simov** [comment]
That was my only guess so far as well. Along with the other updates in this release I also migrated to a new API for writing browser extensions called manifest v3, and quite a few of those changes were worked on and fixed only in very recent chrome releases.
