### ISSUE TITLE
If the subtitle has a hyperlink, clicking the subtitle of the TOC will jump directly to the hyperlink

### ISSUE THREAD

**Issue by DIYer22** [simov/markdown-viewer#203]
![image](https://user-images.githubusercontent.com/10448025/215309877-3848bd44-ba65-4b8c-a3e2-a7c9202a3961.png)

If I click the "矩阵乘法 (Matrix multiplication)" in the Table of Content, will directly to the hyperlink instead of jumping to subtitle

**Comment by DIYer22** [comment]
Here is rendered HTML code
![image](https://user-images.githubusercontent.com/10448025/215310032-8a656891-68c4-4fc2-bd87-3d76d3976b58.png)

**Comment by simov** [comment]
Thanks for reporting this :+1:

**Comment by simov** [comment]
This was fixed in v5.1, header links are no longer picked up by the ToC generation.
