### ISSUE TITLE
Auto reload of file is not working on Edge

### ISSUE THREAD

**Issue by PadreSVK** [simov/markdown-viewer#207]
Hi, thanks for the great extension 🎉🎉

I find out the issue with auto-reload on file change that is not working with Edge `Version 110.0.1587.46 (Official build) (64-bit)` wit markdown viewer Version: 5.0

**Comment by simov** [comment]
Hi, @PadreSVK, auto reload seems to be working on Edge on my end. Can you verify that you are looking at either a locally hosted file on the file:// URL or a site address that resolves to localhost? Markdown Viewer can reload only content on your local machine as outlined [here](https://github.com/simov/markdown-viewer#autoreload).

**Comment by PadreSVK** [comment]
it is local file
![image](https://user-images.githubusercontent.com/8254631/219403076-1fcffc29-caba-4aae-92bc-a94f5ce1f027.png)

I tried also to rename it, but it is not refreshing. After force refresh it rerender the latest version

**Comment by simov** [comment]
Have you enabled the content option for autoreloading? By default that option is disabled.

**Comment by PadreSVK** [comment]
🤦‍♂️ oh my bad, sorry 🙂
