### ISSUE TITLE
Option to ignore YAML front matter

### ISSUE THREAD

**Issue by cvladan** [simov/markdown-viewer#208]
First and foremost, I must express my appreciation and gratitude to the author for his tremendous effort.
Thank you!

Would it be possible to implement a toggle option that would allow the YAML front matter block to be hidden from view?

**Comment by simov** [comment]
This was fixed in v5.1, now YAML and TOML frontmatter is ignored and if a title attribute is present is being used as a title of the document as well - the one you see inside the tab itself.
