### ISSUE TITLE
Not rendering remote file on Firefox

### ISSUE THREAD

**Issue by GokulRajV8** [simov/markdown-viewer#211]
I am running Firefox on Arch Linux with Markdown viewer add-on and a file from remote origin is not getting rendered as shown below despite allowing access and adding all origins in the settings.

![image](https://user-images.githubusercontent.com/47924829/232080015-9fb8666f-d3e0-4d14-9a19-156c27fa0852.png)
![image](https://user-images.githubusercontent.com/47924829/232080237-1724ff0c-7e23-4038-b2a4-ed480c94782b.png)

**Comment by simov** [comment]
Have a look at this document https://github.com/simov/markdown-viewer/blob/main/firefox.md

**Comment by GokulRajV8** [comment]
As per the document, the content is served as `text/plain` but the same content type is added in the settings under `Content Type Detection:` as shown in the screenshot. Kindly help

**Comment by simov** [comment]
It's inside this chapter: https://github.com/simov/markdown-viewer/blob/main/firefox.md#remote-origins-with-strict-csp

> For example, content on GitHub's `raw.githubusercontent.com` won't be rendered even if that origin was enabled inside the Advanced Options page

Your screenshot shows a file served on the `raw.githubusercontent.com`

**Comment by GokulRajV8** [comment]
Got it now. The video was helpful to understand. Thanks for the help and I love your product by the way.
