### ISSUE TITLE
Code block is not working

### ISSUE THREAD

**Issue by decadence** [simov/markdown-viewer#215]
Hello.

Latest Chrome user. As far as I remember code blocks with specified language worked but after some moment they don't. Or what am I doing wrong?

Test file: [test.md](https://github.com/simov/markdown-viewer/files/11673635/test.md)
What I see: ![2023-06-07_10-13-04](https://github.com/simov/markdown-viewer/assets/1434668/7a046314-89e4-4ae7-b8ba-1b1489719e67)

What I expect:
```php
public function escapeLike(string $value, string $char = '\\'): string
{
    return str_replace(
        [$char, '%', '_'],
        [$char.$char, $char.'%', $char.'_'],
        $value
    );
}
```

Settings:
![image](https://github.com/simov/markdown-viewer/assets/1434668/9f3578c9-7a1e-4662-88d8-78751ff54ede)

With "Remark" compiler it's better but no syntax highlight is happening anyway.

![image](https://github.com/simov/markdown-viewer/assets/1434668/e2998825-24f7-481f-b86a-deaa2ff059a7)

Tried with disabling other extensions with no luck.

**Comment by simov** [comment]
That's really strange. The file you posted earlier works on my end. Maybe try clicking on the Defaults button inside the popup. This will reset your theme selection and the compiler and content options. If that doesn't work then try to re-install the extension.
