### ISSUE TITLE
How do I change the rendered markdown Theme?

### ISSUE THREAD

**Issue by dattasid** [simov/markdown-viewer#221]
When I click "Extension Settings", I do not see a theme option.

I loaded from the extension from markdown-viewer-v5.1.zip 

I only see Origins, Settings, Help . Settings only has: _Extension Icon and Content Favicon Color_: [Light, Dark], _Popup and Options Page Color Mode_: [Light, Dark] . Neither of these changes the rendered page css/theme.

I am looking through the source files in `options/` folder and I do not see any other option.

What am I missing?

PS: If I can change index.css to change the theme, how do I do it?

**Comment by simov** [comment]
Simply click on the extension icon with your left mouse button, there is a popup holding those other settings.

**Comment by dattasid** [comment]
Solved. 😅

Perhaps add 1 line in the README for idiots like me, that clicking on the extension icon in the browser shows this menu, NOT via the Extension Settings link.

**Comment by dattasid** [comment]
Closed

**Comment by simov** [comment]
That's a good suggestion. I'm showing that in the introductory screencast as well https://www.youtube.com/watch?v=mlB-SQVq_oU 

I'll keep this issue open for now

**Comment by simov** [comment]
That's a good suggestion too. Personally I have always thought that the extension's popup on left mouse click was the most convenient way to get to its options, but lots of things has changed in the browser UI in the past 10 years so maybe now it is easier to miss the fact that you can left mouse click on it or pin it so that you can access it easier later on.

**Comment by dattasid** [comment]
>  Personally I have always thought that the extension's popup on left mouse click was the most convenient way to get to its options

It is still the most convenient place. Just that some people might need a reminder, specially since the theme feels like a `Setting` and not a `Action` that is typically on the left click menu.

So a simple statement "Left click the extension icon to change the markdown theme" on the Settings page might be the easiest solution.

A menu directly in the rendered markdown sounds good too, thought probably a bit more work. Suggestion: make it float on the top right as you scroll the page.

**Comment by stdedos** [comment]
Maybe some button inside the TOC? Or a float on either side of the page? (although I don't really like floats, they remind me chatbots i.e., the scourge). Or just "downright" add them also in settings? (and you can still offer them as a extension-icon-left-click shorthand)

**Comment by simov** [comment]
Markdown Viewer v5.3 landed with an improved Advanced Options page where you can click on Settings inside the header and get to all of the options available in the popup:
![Screenshot from 2024-05-04 20-52-40](https://github.com/simov/markdown-viewer/assets/1694112/07ebac22-8b02-47b1-a2bc-34b5fa523c95)

**Comment by dattasid** [comment]
TYVM! Closing issue for now, I think UI is clear now.
