### ISSUE TITLE
Can I pull a theme?

### ISSUE THREAD

**Issue by Tyxiang** [simov/markdown-viewer#222]
This theme will be based on Github theme, but h1 and h2 will be displayed in the center, and there will be no hr line.

**Comment by simov** [comment]
If you want to have a custom theme follow the [manual install](https://github.com/simov/markdown-viewer#manual-install) steps and then update the GitHub theme on your local computer.

**Comment by Esscraye** [comment]
I think you can add style in your markdown file, or link an css file to your markdown to override the extension theme

**Comment by natewind** [comment]
Could you please add an empty theme with no presets in `index.css`? If one wants to develop their own local theme, it’s much easier to start with a predictable blank slate than to fight against the existing styles.

**Comment by simov** [comment]
Custom theme support landed in v5.3, have a look at the [documentation](https://github.com/simov/markdown-viewer?tab=readme-ov-file#custom-theme)

When you select the CUSTOM theme at the bottom of the themes dropdown you get a blank theme, exactly as suggested above. Then you can add a style tag in your markdown and create your own theme, here is an [example](https://gist.github.com/simov/2a074a1c0123e6ba4bc2bfa6a67d3203). Once you are ready go to the Advanced Options page and click on Settings in the header, if the CUSTOM theme is selected there will be a button below to select your .css file and make it permanent. Don't forget to remove the inline tag from your document. You can also update or remove the uploaded custom theme.
