### ISSUE TITLE
Please support loading custom CSS styles

### ISSUE THREAD

**Issue by zhouxinghong** [simov/markdown-viewer#223]
Please support loading custom CSS styles

Hello!
The extension performs great! Please support loading custom CSS styles so that the extension can meet more usage scenarios.

System environment:
Chrome is up to date
Version 120.0.6099.110 (Official Build) (64-bit)
Windows 10
Extended version: 5.2.1

**Comment by zhouxinghong** [comment]
Thank you very much for providing a super excellent Markdown preview extension! 👍😜🎉

**Comment by simov** [comment]
Custom theme support landed in v5.3, have a look at the [documentation](https://github.com/simov/markdown-viewer?tab=readme-ov-file#custom-theme)

When you select the CUSTOM theme at the bottom of the themes dropdown you get a blank theme. Then you can add a style tag in your markdown and create your own theme, here is an [example](https://gist.github.com/simov/2a074a1c0123e6ba4bc2bfa6a67d3203). Once you are ready go to the Advanced Options page and click on Settings in the header, if the CUSTOM theme is selected there will be a button below to select your .css file and make it permanent. Don't forget to remove the inline tag from your document. You can also update or remove the uploaded custom theme.
