### ISSUE TITLE
Auto-Reload Not Working for Local .md Files in Firefox

### ISSUE THREAD

**Issue by heltonricardo** [simov/markdown-viewer#229]
**Description:**
The auto-reload feature, designed to update when a local .md file changes, is not working as expected.

**Steps to Reproduce:**
1. Open Firefox on Microsoft Windows.
2. Install Markdown Viewer extension.
3. Open a local .md file using the extension.
4. Make changes to the .md file and save it in an external editor (e.g., Visual Studio Code with Auto-Save enabled).

**Expected Behavior:**
Auto-reload should update the file without manual intervention.

**Actual Behavior:**
Auto-reload is not functioning, requiring a manual refresh to see updates.

**Environment:**
- Extension Version: 5.2.2
- Firefox Version: 122.0 (64-bit)
- Operating System: Microsoft Windows [Version 10.0.19045.3930]

**Additional Information:**
Verified Auto-Save is enabled in Visual Studio Code. A screenshot illustrating the issue is attached.

![image](https://github.com/simov/markdown-viewer/assets/50843386/d4395d77-b8bd-4dd0-bb45-ff8739c970ec)

Thank you for your attention. Let me know if further information is needed.

Best regards,
Helton.

**Comment by simov** [comment]
Hi, thank you for the detailed bug report.

This is a known limitation of the extension when used in Firefox. You can read about it here: https://github.com/simov/markdown-viewer/blob/main/firefox.md

You will have to setup a small file server on your workstation and access your files on localhost instead. In that document there is an example of running such file server using Node.js, but any other software could work as long as it servers the markdown files with `text/plain` content type.

**Comment by heltonricardo** [comment]
Thanks for the quick response and directing me to the documentation. I missed checking the repository documentation and appreciate your guidance. I'll explore the suggested workaround using a local file server.
