### ISSUE TITLE
Possibility to **exclude** some domains from "Allow all"?

### ISSUE THREAD

**Issue by twardoch** [simov/markdown-viewer#23]
I’d like to principally “allow all” matching URLs but I’d like to exclude those on github.com, because Github includes `.md` etc. in regular URLs, e.g. `https://github.com/simov/markdown-viewer/blob/master/README.md` is a HTML document, and if I enable “Allow all” then the extension is trying to process it, leading to odd results (some items are badly shifted). 

I see that it’s not possible to use regexes in the domain section of the options, right? I tried `^(?:(?!github\.com))` but the extension didn’t add this pattern to the list.

**Comment by simov** [comment]
Interesting idea, I've never thought about it. I'll think about a possible solution.
Thanks for the feedback!

**Comment by techdad** [comment]
Thanks for thinking about a possible solution. I have the exact same request for the same reason.

**Comment by simov** [comment]
Hi there!

@twardoch @techdad I've updated the documentation. Take a look at the [Allow All Origins](https://github.com/simov/markdown-viewer#allow-all-origins) section. Read carefully through the example in that section, you'll find exactly what you need.
