### ISSUE TITLE
Mermaid.js out of date (9.2 rather than 10.8) in Firefox store

### ISSUE THREAD

**Issue by norru** [simov/markdown-viewer#230]
I have installed the extension from the Firefox store. It works great, but unfortunately it uses Mermaid.js 9.2.2, and the graphs I need displaying appear to require a more recent version.

Would it be possible to make a new extension release with an up to date mermaid? I see https://github.com/mermaid-js/mermaid/releases/tag/v10.8.0 is latest at the time of writing.

**Comment by simov** [comment]
Yes, that is a known limitation of the Firefox version and I will be looking at resolving it in the next release. I was having problems loading newer versions of Mermaid in Firefox.

**Comment by simov** [comment]
Release may take awhile, but it will definitely happen. I will let you know once I have it ready.

**Comment by simov** [comment]
Markdown Viewer v5.3 just got approved on AMO with Mermaid updated to v10.8.0.

**Comment by avinashkurup** [comment]
> Thanks for looking into this, I confirm that the issue is Firefox specific, and my graphs look fine in Markdown Viewer in Chrome. I hope you get around to make a new release soon as having to juggle browsers around just for Mermaid is a bit of a faff.
> 
> Keep up the great work!

I have just started using this cool extension in Google Chrome, its great! but I have issues (only mermaid scripts displayed, no diagrams) with my mermaid scripts embedded in markdown. Please help!

**Comment by simov** [comment]
@avinashkurup check out the [markdown syntax](https://github.com/simov/markdown-viewer?tab=readme-ov-file#mermaid) needed, also you need to enable the `mermaid` option in the extension's settings.
