### ISSUE TITLE
custom define style

### ISSUE THREAD

**Issue by vegalou** [simov/markdown-viewer#231]
New Feature request, if there is a field, user could setup prefered style(font-size, color...)

Currently, `Modify extension XPI` & `disable auto Update` works.

eg: Smaller mono width font in **Quote** for Code, or other **Highlight Efeects**.

This utility usually found in Markdown viewer & Editor.

Thanks!

**Comment by simov** [comment]
Custom theme support landed in v5.3, have a look at the [documentation](https://github.com/simov/markdown-viewer?tab=readme-ov-file#custom-theme)

When you select the CUSTOM theme at the bottom of the themes dropdown you get a blank theme. Then you can add a style tag in your markdown and create your own theme, here is an [example](https://gist.github.com/simov/2a074a1c0123e6ba4bc2bfa6a67d3203). Once you are ready go to the Advanced Options page and click on Settings in the header, if the CUSTOM theme is selected there will be a button below to select your .css file and make it permanent. Don't forget to remove the inline tag from your document. You can also update or remove the uploaded custom theme.

**Comment by vegalou** [comment]
Dear @simov :

Thanks for your improvement. 

`markdown-viewer` works GREAT in editing MD works.

**THANKS AGAIN.**
