### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by HaleTom** [simov/markdown-viewer#24]
I'm using markdown to take notes on machine learning, which requires a good few formulae.

Can this plugin support MathJax?

**Comment by simov** [comment]
Thanks for the feedback, @HaleTom, this is definitely on my TODO list. I'll let you know once I have something ready.

**Comment by HaleTom** [comment]
Thanks @simov.

I've found a temporary but ugly work around: 

https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl?utm_source=chrome-app-launcher-info-dialog

The formulae look like they're rendered by HTML rather than MathJax but at least they're readable for now.

**Comment by simov** [comment]
@HaleTom @huangjj27 @adius I've just pushed the MathJax support to master. You can pull and test if you want, any feedback before publishing it into the wild is greatly appreciated.

For the time being the documentation isn't updated yet but here is what you should know:

---

### MathJax

The following `mathjax` delimiters are supported:

- inline math: `\(math\)` and `$math$`
- display math: `\[math\]` and `$$math$$`

The following rules apply to your content when `mathjax` is enabled:

- Regular dollar currency sign `$` in text that is not part of a math should be escaped: `\$6.20`
- Regular markdown escaping for parentheses and brackets no longer works: `\(some text\)` and `\[some text\]` will always be converted to math expressions unless they are wrapped in backticks or fenced code blocks.

---

Let me know what do you think.

Also I've pushed a new test syntax file for MathJax here: https://raw.githubusercontent.com/simov/markdown-viewer/master/test/mathjax.md it contains the samples from the MathJax repo and some other math formulas.

I've added a MathJax section in the base syntax file as well: https://github.com/simov/markdown-viewer/blob/master/test/syntax.md#mathjax just to be able to test it alongside with all other markdown features.

**Comment by HaleTom** [comment]
Cheers! That's great news!

Just checking, did you mean `\$6.20` or just `\$`?

Call me dopey, but what's the procedure for using the test version?

**Comment by simov** [comment]
Just the dollar sign `\$`.

Here is the procedure:

1. Clone this repo
2. Navigate to `chrome://extensions`
3. Make sure that the `Developer mode` checkbox is checked at the top
4. Disable the Markdown Viewer extension downloaded from the Chrome Store
5. Click on the `Load unpacked extension...` button and select the cloned directory

After done testing you can disable the local version and re-enable the other one downloaded from Chrome Store.

**Comment by HaleTom** [comment]
I get this:

![example](https://i.imgur.com/bPSV39d.png)

----

If I disable the dev version of Markdown Viewer, it displays as raw text, so I hope this means I'm doing it right.

**Comment by simov** [comment]
It should be rendered as MathJax, did you turned it on?
![mathjax](https://user-images.githubusercontent.com/1694112/31491511-45b81c02-af50-11e7-9a10-1319a1c278f9.png)

**Comment by simov** [comment]
@HaleTom actually my bad, the MathJax support currently works only for local and sites without strict Content Security Policy (CSP) set. With the current implementation you won't be able to see math formulas for files hosted on GitHub.

**Comment by simov** [comment]
The MathJax support is published in version 3.2

You can read about the current implementation and its limitations here: https://github.com/simov/markdown-viewer#mathjax

Any feedback is greatly appreciated!

**Comment by HaleTom** [comment]
Thanks a bunch!

I've been busy but am just about to get back to AI learning (which requires formulae in my notes).
