### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by Gray388** [simov/markdown-viewer#244]
Hello, I'm trying to upload my css theme, but it's larger than 8 kb.
Can you make a theme larger than 8 kb load?

**Comment by simov** [comment]
No, that is a limitation of the sync storage that the extension is using. 

Generally speaking 8KB should be more than enough for a markdown theme, but in case yours is larger than that it might need some trimming.

**Comment by Gray388** [comment]
Got it, thanks.
