### ISSUE TITLE
Handling as ‘escape’ issue about the parenthesis ‘)’ 

### ISSUE THREAD

**Issue by colap** [simov/markdown-viewer#25]
We are currently running with Chrome extension and 
I personally think this is a great and useful function. 

In the case of 
`[Monit](https://192.168.2.141:20080/failsafe\(monit\).md)`

it’s not handling as escape due to there’s 
`Monit.md)`
exist. 

Thank you.

**Comment by simov** [comment]
Hi @colap, can you try with the Remark compiler:

![](https://user-images.githubusercontent.com/1694112/29241913-d89d9bd6-7f8b-11e7-86fb-e8b64b3fffbb.png)

**Comment by colap** [comment]
It works :)
