### ISSUE TITLE
Anomaly in ChatGPT markdown file display

### ISSUE THREAD

**Issue by TJOnline2112** [simov/markdown-viewer#251]
![CHATGPT - MarkdownPreview comparison](https://github.com/user-attachments/assets/45b61a54-6918-48f6-981a-fd7c4cd68328)

Hello, new to Github (hope this is a 'bug ticket') and am exploring Markdown-Viewer.  It's very nice, except for an anomaly.  Notice that in the attached image, MV consistently echoes whatever formula it encounters in plain text.  In the image, those are "limx->3 x-3x2-9" and "limx->0 xsin(3x).  Maybe my settings are screwy?  I'm trying to transform the markdown MD files exported by Chat-GPT Math Solver into PDFs for viewing and printing.  Thanks much.

**Comment by simov** [comment]
Can you copy/paste the precise markdown syntax here? Also make sure that the `mathjax` option is enabled.

**Comment by TJOnline2112** [comment]
I've included the following.  Hope this helps.

![example of Problem](https://github.com/user-attachments/assets/920a5c99-3c14-4950-b5f9-8dd4562da9cc)
(a comparison of the relevant portions of the Markdown Viewer and CHATGPT appearances)

![settings](https://github.com/user-attachments/assets/25f70861-5607-4dd4-9194-afdbbc56f25c)
(all of my settings currently)

[portion of ShortQuiz.md](https://github.com/user-attachments/files/16674732/portion.of.ShortQuiz.md)
(a portion of ShortQuiz.md beginning with '1. Determine' and ending with 'diverges.' Presumably the anomaly is in that section.)

[ShortQuiz.md](https://github.com/user-attachments/files/16674739/ShortQuiz.md)
(the entire original ShortQuiz.md file, if that is helpful)

**Comment by TJOnline2112** [comment]
![example of Problem](https://github.com/user-attachments/assets/f2ce2043-9a87-4a4f-9a1e-83236116296d)
Here's a specific as appears relative to the original CHATGPT chat.

![settings](https://github.com/user-attachments/assets/e32ac267-6e1c-431c-bae7-6d6369696fd9)
Here are my settings.

[portion of ShortQuiz.md](https://github.com/user-attachments/files/16682922/portion.of.ShortQuiz.md)
Here is the portion of the MD file between the text "1. Determine" and the text "diverges."  I assume the anomaly is somewhere in between.

[ShortQuiz.md](https://github.com/user-attachments/files/16682932/ShortQuiz.md)
Here is the entire MD file, if it helps.  Thx

**Comment by simov** [comment]
Thanks for the detailed bug report.

To be fair though, that's [MathML](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math) syntax, meaning part of HTML and not Markdown in any way. You can change the file extension of your document above and load it directly in your web browser. You will see that the exact same error is present there, meaning the MathML syntax provided is incorrect and the browser does not know how to render it correctly.

Looking at the attached HTML, the outer most tag contains a class called `katex`, meaning most likely the web app was using [katex](https://katex.org/) to render the math equations, but then the export to MathML was incorrect, I assume.

**Comment by TJOnline2112** [comment]
Thank you so much for your time, which I've apparently wasted, Simov.  Tried your suggestion and sure enough, you are exactly right.  It appears that my issue is with CHATGPT and not Markdown-Viewer at all.  And thanks for your insight.  Cheers.
