### ISSUE TITLE
Chinese characters in title are ignored when content table is generated

### ISSUE THREAD

**Issue by xc1427** [simov/markdown-viewer#26]
If There is a title which contains both latin letters and chinese characters such as "三级标题 h3 in chinese", only the english part is converted into an HTML internal link. The URL is like:
```
file:///file_path/markdown_viewer_bug_test.md#-h3-in-chinese
```

Try this file:
[markdown_viewer_bug_test.md.zip](https://github.com/simov/markdown-viewer/files/1219802/markdown_viewer_bug_test.md.zip)

Generally, to handle chinese character we need to do encoding in UTF-8. For example, 
https://zh.wikipedia.org/wiki/万维网联盟
is actually
https://zh.wikipedia.org/wiki/%E4%B8%87%E7%BB%B4%E7%BD%91%E8%81%94%E7%9B%9F

**Comment by simov** [comment]
Can you try with the `Remark` parser?
![remark](https://user-images.githubusercontent.com/1694112/29241913-d89d9bd6-7f8b-11e7-86fb-e8b64b3fffbb.png)

**Comment by xc1427** [comment]
`Remark` doesn't have this issue. 👍
