### ISSUE TITLE
Improve reading experience by adjusting line length

### ISSUE THREAD

**Issue by jschlieber** [simov/markdown-viewer#27]
IMHO the line lengths are to long for fast and fluent reading at the line breaks.

http://practicaltypography.com/line-length.html
https://en.wikipedia.org/wiki/Line_length

Making the column width adjustable (other than the fixed 888px) would also be a simple possibility here...

Compare (888px):
<img width="1249" alt="screen shot 2017-08-17 at 13 58 12" src="https://user-images.githubusercontent.com/11458212/29411216-27b21aaa-8354-11e7-98df-479978dab712.png">

with (550px, edited with developer tools):
<img width="1237" alt="screen shot 2017-08-17 at 13 59 40" src="https://user-images.githubusercontent.com/11458212/29411251-5ac32696-8354-11e7-833e-75ce033d5c0b.png">

...concerning readability

**Comment by simov** [comment]
Hi @jschlieber, thank you for your input!

Currently all other themes except the two GitHub ones, have a responsive width, meaning that if you open up your Developer Tools vertically or resize your entire browser window, you can kind of achieve what you want:

![screenshot from 2017-08-18 17-05-39](https://user-images.githubusercontent.com/1694112/29462305-9314f392-8437-11e7-8001-cfb080e04af6.png)

The GitHub theme is using the exact css styles found on the GitHub's repository Readme view. The reason why is to get a rendered version of your Markdown as close as possible to what you'll get once you push your documents on GitHub.

I'll think about adding an option for varying document width.

**Comment by simov** [comment]
There is a new `Width` option available in Markdown Viewer v5 that allows you to fix the content width to any of the available presets there. You can download the latest version from Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section here.
