### ISSUE TITLE
YAML metadata + TOC, Marked compiler

### ISSUE THREAD

**Issue by almereyda** [simov/markdown-viewer#29]
At times, MarkDown documents come with additional YAML metadata at the beginning of a document. This is often referred to as a *frontmatter* and is indicated by triple dashes in the first line and after the YAML keys.

Currently the Marked compiler renders it as a horizontal rule, the raw data structures written out and a third-level headline in the beginning of the document and as such the false headline also at the beginning of the Table of Contents (ToC).

**Comment by simov** [comment]
The problem stems from the fact that [Marked](https://github.com/chjj/marked) doesn't support [Markdown Front Matter](https://jekyllrb.com/docs/frontmatter/).

Does Remark work for you?

**Comment by simov** [comment]
The fix is published in version 3.2 - Markdown Front Matter is supported with the **Remark** compiler.
