### ISSUE TITLE
Match gitlab readme

### ISSUE THREAD

**Issue by janstuemmel** [simov/markdown-viewer#3]
gitlab readmes are matched by your app, would be nice if you add gitlab to exclude_matches in manifest json

**Comment by simov** [comment]
That's a good idea, there are other sites that renders the markdown as well.

**Comment by simov** [comment]
@janstuemmel I just excluded both bitbucket.org and gitlab.com here https://github.com/simov/markdown-viewer/commit/ba0e30a5526d9dcd6866ee3324afa73d6cca2027

Do you have any update on your other issue #2, because I'm going to release a new version soon.

**Comment by simov** [comment]
Published version 1.7 it will be live withing an hour.
