### ISSUE TITLE
Support for ToC themes

### ISSUE THREAD

**Issue by almereyda** [simov/markdown-viewer#30]
The Remark compiler does not apply the selected theme to the Table of Contents. The Marked compiler however applies it partly, and only for first level headlines, which are presented as links.

Lower levels unfortunately do not inherit a theme's font setting in any way.

**Comment by simov** [comment]
Currently there is no theme support for the TOC sidebar. The themes are applied only on the markdown content.

**Comment by simov** [comment]
Markdown Viewer v5 got released earlier this month with 30 new themes and all of them are being applied on the ToC sidebar as well. You can download it from the [release](https://github.com/simov/markdown-viewer/releases/tag/5.0) section and from the Chrome Web Store.
