### ISSUE TITLE
\< does not works

### ISSUE THREAD

**Issue by 1vanK** [simov/markdown-viewer#31]
for example
```
SharedPtr\<Object\>
```
result:
```
SharedPtr\
```

**Comment by simov** [comment]
Using the `Remark` compiler the result is:

![remark](https://user-images.githubusercontent.com/1694112/31459150-f9754610-aeca-11e7-847f-95c1a4c0f215.png)


```
SharedPtr\<Object>
```

So the escaping isn't working correctly even with `Remark` but if you escape only the second bracket like this `SharedPtr<Object\>` it yields the expected result.

**Comment by 1vanK** [comment]
Thanks!
