### ISSUE TITLE
Markdown Checkbox support broken.

### ISSUE THREAD

**Issue by larrydewey** [simov/markdown-viewer#33]
You should be able to us `- [ ]` to create a todo list action, but it does not render it properly.

Expected:
- [ ] Like this

Actual:
- `[ ]` Like this

**Comment by simov** [comment]
Try with the Remark compiler:
![remark](https://user-images.githubusercontent.com/1694112/30495294-24a68eba-9a54-11e7-9254-fe846ba506b5.png)

**Comment by huangjj27** [comment]
It's with **REMARK** compiler that task support broken!
![image](https://user-images.githubusercontent.com/8068443/30680938-fd9b6158-9ed4-11e7-9e74-93ada23409f7.png)
![image](https://user-images.githubusercontent.com/8068443/30680945-0b1ced06-9ed5-11e7-89a8-550fcb9d40fc.png)
Do I miss something?

**Comment by simov** [comment]
You should *disable* the `sanitize` option. Sanitize means that all HTML tags in your Markdown document will be ignored, and for some reason that disables the GFM Task Lists as well.

**Comment by huangjj27** [comment]
@simov  thanks! it works!
