### ISSUE TITLE
Back anchor in footnote can have a better style

### ISSUE THREAD

**Issue by huangjj27** [simov/markdown-viewer#35]
as in the picture below, the back anchor start in a new line: 
![image](https://user-images.githubusercontent.com/8068443/30688470-d772f754-9ef0-11e7-9a0e-4b39577d5fc2.png)

what about make it appear at the end of relevant footnote like this:
![image](https://user-images.githubusercontent.com/8068443/30688603-3b8512cc-9ef1-11e7-952c-37971a990fec.png)

I think minor change will make it more clear about which footnote the back anchor goes.

**PS**: I was using `remark` for rendering

**Comment by simov** [comment]
This is looking weird indeed, thanks for the feedback!

**Comment by huangjj27** [comment]
Is this a behavior of the compiler? I try to fix this by myself but failed. All I jumped into are the refered codes.

**Comment by simov** [comment]
It is a compiler issue regarding Remark. You can read about it here: https://github.com/syntax-tree/mdast-util-to-hast/pull/15

**Comment by vhf** [comment]
FYI the fix for this issue has been merged: https://github.com/syntax-tree/mdast-util-to-hast/pull/15

**Comment by simov** [comment]
Thanks @vhf I'll take a look at it shortly.

**Comment by spectras** [comment]
Not it has not.
In fact, #15 now makes inline footnotes, which were not affected, also show the same issue.

→ By wrapping the footnote in a `P` element and forcing the backlink outside, the backlink can no longer appear at the end of the line.

Which is a pity, since having the backlink at the end of the line is the most common way.

**Comment by simov** [comment]
Yes, the problem persists, that's why I haven't closed the issue yet.

**Comment by simov** [comment]
Seems to be fixed in Markdown Viewer v5.2 for both of the compilers that has support for footnotes: `remark` and `markdown-it`.
