### ISSUE TITLE
Reload on file change

### ISSUE THREAD

**Issue by surmann** [simov/markdown-viewer#37]
Hallo,

What do you think about a feature to reload files automatically when it changes in the background?
An alternative would be to reload (or check) the file in a fixed time interval.

Kind regards,
Dirk

**Comment by grrttedwards** [comment]
I'll try to work on this and submit a PR. I came here to request this!

**Comment by grrttedwards** [comment]
After looking at the way that the content is styled, this is a much larger change than I would have anticipated...
The file is never really "looked at", and instead the content is styled after Chrome has finished loading the file. Refreshing the browser causes the unstyled flash you see when loading a file, so it's not viable just to reload on a timer.
Perhaps a solution involves watching the modified time property on the file and manually injecting the changes into the DOM then updating the styling.

**Comment by simov** [comment]
This feature landed in v3.6 Check out the Content tab in the popup, there is a new option called `autoreload`.

**Comment by yangmillstheory** [comment]
Is there a way to avoid the [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) on reload?

**Comment by simov** [comment]
Currently no. I have tried to minimize it as much as possible.
