### ISSUE TITLE
TOC not supporting non-ascii characters

### ISSUE THREAD

**Issue by fxmy** [simov/markdown-viewer#39]
When headers in the .md file consist no alphanumeric characters, the TOC falls back to generate anchor link of '#-'.
This results in multiple TOC items jump to the same content, whence is the first occurrence of the non-alphanumeric header.
Maybe consider adding auto prefixes to the generated anchor link to mitigate this issue?

**Comment by simov** [comment]
Hi @fxmy,

Try with the `Remark` compiler instead:

![remark](https://user-images.githubusercontent.com/1694112/32050233-bcd9bbe8-ba58-11e7-9cab-1f24834e7bbf.png)

**Comment by fxmy** [comment]
Thanks, @simov , that works like a charm
