### ISSUE TITLE
ignores <pre> tags

### ISSUE THREAD

**Issue by radiovisual** [simov/markdown-viewer#4]
I have the following `<pre>` tag:

<pre>
     src /
        content/
        images/
        scripts/
        styles/
     
     templates/
        partials/ 
</pre>

In Chrome, the markdown-viewer extension renders a flat string:

```<pre> src / content/ images/ scripts/ styles/ templates/ partials/ </pre>```

Whereas, the same `<pre>` tags renders perfectly when posted to github.

**Comment by simov** [comment]
Hi, @radiovisual, by default the *marked* compiler, that this extension uses, disables the rendering of HTML tags. You can read about it [here](https://github.com/chjj/marked#sanitize).

If you want the HTML tags rendered, make sure you uncheck the *sanitize* option:

![sanitize](https://cloud.githubusercontent.com/assets/1694112/9311725/dc39dbbc-4520-11e5-8d06-ed010fac6a42.png)

The compiler options are stored, so you won't have to change it again.

**Comment by radiovisual** [comment]
Thanks @simov, I appreciate it. Awesome extension, btw. I use it all the time.

**Comment by simov** [comment]
Yeah, me too :smile:
