### ISSUE TITLE
pre/code not formatted properly with some theme

### ISSUE THREAD

**Issue by wzhliang** [simov/markdown-viewer#40]
With some theme, the pre/code section that starts with 4 spaces are all squashed to the left edge, ignoring the space characters inside. 

One of such theme is GODSPEED. Themes like GHOSTWRITER works as expected.

**Comment by simov** [comment]
Hi @wzhliang, can you copy/paste an example markdown snippet here, so that I can reproduce it?

**Comment by wzhliang** [comment]
```
# Code

    hello
      world
```

# Code

    hello
      world

**Comment by simov** [comment]
Removing the `pre` tag from here: https://github.com/simov/markdown-viewer/blob/master/themes/godspeed.css#L220 solves the issue.

The fix will be published with the next release :+1:

**Comment by simov** [comment]
The fix is published in version 3.2
