### ISSUE TITLE
Firefox version breaks GitHub

### ISSUE THREAD

**Issue by Keith94** [simov/markdown-viewer#41]
1. Install the extension
2. Load github.com

![image](https://user-images.githubusercontent.com/5490615/32815595-aadbfec2-c969-11e7-9041-be7b2f2f9b7b.png)

**Comment by simov** [comment]
Something is very wrong with the Firefox at the moment. I can't get it to work on FF 57 because no `content_scripts` can be injected into the pages. That's a huge problem, hopefully Mozilla will resolve it soon.

**Comment by simov** [comment]
I've found the problem, will publish new release soon.

**Comment by simov** [comment]
@Keith94 I've pushed the fix in v3.2

Here is how I use it locally on my machine:

```js

var express = require('express')
var serveIndex = require('serve-index')
var serveStatic = require('serve-static')

var app = express()

// serve markdown files with content-type: text/plain in Firefox
app.use((req, res, next) => {
  if (/Firefox/.test(req.headers['user-agent'])) {
    var match = '\\.(?:markdown|mdown|mkdn|md|mkd|mdwn|mdtxt|mdtext|text)(?:#.*|\\?.*)?$'
    if (new RegExp(match).test(req.url)) {
      res.setHeader('content-type', 'text/plain; charset=utf-8')
    }
  }
  next()
})

app.use(serveStatic('/home/s'))
app.use('/', serveIndex('/home/s', {'icons': true, view: 'details'}))

app.listen(8001)
```

I'm running a NodeJS (Express) server in the background that serves my home folder.

---

I'm working on the upcoming release where this won't be needed, but the extension will require a bit more permissions to operate. I'll let you know once it's out.

**Comment by Keith94** [comment]
Thanks, I updated to v3.2 but it's still bugged on this page: https://github.com/simov/markdown-viewer/blob/master/README.md

![image](https://user-images.githubusercontent.com/5490615/32856968-3585337c-c9fb-11e7-98fd-e46190a2e0a3.png)

**Comment by Keith94** [comment]
Also, the extension doesn't seem to be working on the "raw" version: https://raw.githubusercontent.com/simov/markdown-viewer/master/README.md

**Comment by simov** [comment]
Thanks for your feedback @Keith94 

About the first issue - that's something I didn't expect to happen but it should be fixed in the next release.

About the second issue on the 'raw' version - that's totally expected. FF > 57 have implemented stricter Content Security Policy (CSP) and GitHub in particular enforces it. That's why I showed you my local Express server because currently that's the only why you can use the extension on FF > 57.

Luckily the fix is fairly easy and hopefully by the next week I'll be ready with it. Of course as I mentioned earlier the extension will require more permissions.

**Comment by Keith94** [comment]
OK thanks. I found that changing `security.csp.enable` = `false` works around the second issue at least.
But occasionally the formatting is broken or page is completely blank even with CSP disabled.

![image](https://user-images.githubusercontent.com/5490615/32865481-354bc548-ca18-11e7-90a1-de32e26ba8a3.png)

![image](https://user-images.githubusercontent.com/5490615/32865590-9a173782-ca18-11e7-97e5-23950aaf7be8.png)

**Comment by simov** [comment]
> security.csp.enable = false

Where exactly do you enable that option?

> occasionally the formatting is broken or page is completely blank

That's a total mystery to me too. Also the popup animation is very sluggish on my end. The good news is that on FF 59 Nigthly the performance is noticeably better. Still not perfect but at least they are working on it.

**Comment by Keith94** [comment]
>Where exactly do you enable that option?

Go to `about:config` in a new tab and search for `security.csp.enable`. Then toggle its value to `false`.

**Comment by simov** [comment]
@Keith94 almost there :) 
`security.csp.enable` is a nice tip however that's a huge security issue for all sites you visit so most of the people wouldn't enable it.

**Comment by simov** [comment]
@Keith94 v3.3 is published, here is what you should know:

- Only Firefox Quantum >= 57 is supported!
- The extension's performance on FF 57 is pretty bad, however on Firefox Nightly 59 it works great today!
- So either switch to Nightly (if you can) or hang tight - Mozilla are working on it!

Differences with the Chrome version:
- Doesn't support access to file URLs
- Doesn't use header detection, only Path Matching
- It's not an event page
- The CSP issues found in the Chrome version are not present here

So you'll have to enable all remote origins manually just like in the Chrome version. The only issue is that the performance of the popup and the options page on FF 57 is pretty terrible. You won't need to disable CSP for your entire browser though.

https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-chrome/

Let me know what do you think :+1:

**Comment by Keith94** [comment]
Interesting, well basically I want the add-on to do a few things:

* Apply to any file URLs (my main use case)
* Apply to any "raw" pages (like on GitHub)
* Don't break pages like: https://github.com/simov/markdown-viewer/blob/master/README.md

What would be the regex I need under the "Allowed Origins" to make that possible?
(I found using "Allow all" allows file URLs to work)

I do run Nightly as my only browser for years now.

**Comment by simov** [comment]
The fille:// entry in the list of allowed origins is the last thing I forgot to *hide* in the Firefox version. Access to file URLs **does not work** in Firefox!

For remote origins I use the [webRequest](https://developer.chrome.com/extensions/webRequest)'s `onHeadersReceived` [here](https://github.com/simov/markdown-viewer/blob/3.3/background/background.js#L276-L289). This allows me to override the the `content-type` header and remove the `content-security-policy` for all allowed origins.  But the `onHeadersReceived` event is not available for file:// URLs.

The other possible solution would be if Firefox allows you to open Markdown files inside the browser, like in Chrome they are rendered as plain text.

![firefox-markdown](https://user-images.githubusercontent.com/1694112/33201650-1e4ac61e-d102-11e7-8ad2-c2c20e1cfff1.png)

But as you can see there is no way to do that.

I'm open for suggestions, if there is a way to implement file:// access for Firefox - I would definitely do it.

---

About the remote origins:

I'm thinking about a new `preset` option that will make the path matching configuration a bit easier.

For example I could add the origins that at least I know about in that preset:

- **rawgithubusercontent.com** - the default one `\.(?:markdown|mdown|mkdn|md|mkd|mdwn|mdtxt|mdtext|text)(?:#.*|\?.*)?$`
- **bitbucket.org** - the default one `\.(?:markdown|mdown|mkdn|md|mkd|mdwn|mdtxt|mdtext|text)(?:#.*|\?.*)?$`
- **github.com** - `exclude` - that's just a random string that won't match, needed only if you enable `All Origins`
- **gitlab** - slightly modified `.*\/raw\/.*\.(?:markdown|mdown|mkdn|md|mkd|mdwn|mdtxt|mdtext|text)(?:#.*|\?.*)?$`

And we can extend that list over time with more *known* origins that serve raw markdown.

**Comment by Keith94** [comment]
For opening local file URLs, this workaround might help: https://github.com/KeithLRobertson/markdown-viewer/issues/2#issuecomment-321940542

**Comment by simov** [comment]
Yep, I read about it at some point but I haven't tried it myself. I'll try it and probably document it as workaround. Either way that's something that user should do manually.

**Comment by simov** [comment]
@Keith94 I've added a short screencast: https://youtu.be/lAwJgJn6sUE (no sound)
