### ISSUE TITLE
Custom style sheets

### ISSUE THREAD

**Issue by JonathanHolvey** [simov/markdown-viewer#43]
Would it be possible to add an option to override specific CSS rules in a chosen theme?

For example, I'd like to be able to specify a maximum width for images, while using the default GitHub theme. A field in the advanced options, where I could enter my own CSS, would allow me to achieve this:

```css
.markdown-body img {
    max-width: 20em;
}
```

The `.markdown-body` class selector would be required to override the specificity of the default stylesheet (which is annoying and confusing), however just appending this CSS to the end of the selected theme style sheet would be all that's required to get it working.

**Comment by simov** [comment]
Thanks for the feedback! I had a similar feature request in the past and I'm thinking about a good way to implement it. In the meantime you can use additional styling extension to override the styles that you want.

**Comment by JonathanHolvey** [comment]
I found that placing a `<style>` tag at the end of the document was a simple solution to this. Previously I tried putting it at the top, which causes the Markdown parsing to fail.

**Comment by lmunch** [comment]
Custom style sheet support would be awesome!

**Comment by jibreil** [comment]
Is this feature still coming? I love this extension but none of the themes look great to me and I actually edited the Godspeed theme to something that I prefer but now I've found there's no way for me to use it.

**Comment by simov** [comment]
Yes, it's scheduled for the next release. I'll let you know when it's ready.

**Comment by jibreil** [comment]
:+1:

**Comment by anyfactor** [comment]
Was this feature implemented?

**Comment by simov** [comment]
No, I actually abandoned it due to multiple issues with it. For now you can use other extensions in combination with Markdown Viewer to modify the rendered output.
