### ISSUE TITLE
Firefox version can't open .md file from file system

### ISSUE THREAD

**Issue by huangjj27** [simov/markdown-viewer#44]
It may be the behaviour priority of firefox 57(default to give me a choice to save the file or to open it with  other local  that causes the unrecognizing of such files.

and from the issue https://github.com/simov/markdown-viewer/issues/12, I know that the firefox version does still not to get local markdown file rendered. When will it get support?

![image](https://user-images.githubusercontent.com/8068443/33171339-aba5c04e-d086-11e7-9692-bda8c7906dad.png)

**Comment by simov** [comment]
That's completely up to Mozilla. I'm not aware of a way to override the `content-type` header for local file:// URLs, like I do for the remote ones.

**Comment by huangjj27** [comment]
Is that means there still many differences between Firefox and chrome web extensions that prevent the same code be used for both version?

**Comment by simov** [comment]
There are still a few differences here and there, yes.

The problem with local file:// URLs is not a WebExtensions related. The problem is that there is no way for the user to configure the browser's behavior for handling Markdown files.

Check out this menu on FF: `about:preferences#applications`

**Comment by simov** [comment]
For a longer explanation read this https://github.com/simov/markdown-viewer/issues/41#issuecomment-346776643

**Comment by simov** [comment]
@huangjj27 I've added a short screencast: https://youtu.be/lAwJgJn6sUE

**Comment by huangjj27** [comment]
@simov thanks! but I can't watch the vedio right now (as is known to all, In China mainland Google and YouTube are blocked by the GFW), I'll watch it once I have access to it.
