### ISSUE TITLE
Add print styling

### ISSUE THREAD

**Issue by Tomassie91** [simov/markdown-viewer#45]
Thanks for writing this great plugin! It's great for previewing markdown files. I also use it to convert markdown to PDF, using the print functionality of my browser. Unfortunately, there aren't any print styles in the themes. This adds a border to the GitHub theme, as Huangjj27 noted in #36. It also creates awkward page-breaks, which can be really annoying.

I would greatly appreciate any improvement in this area.

**Comment by simov** [comment]
Thanks for the feedback @Tomassie91 it's definitely on my TODO list.

**Comment by simov** [comment]
I added some [print styling](https://github.com/simov/markdown-viewer/blob/5.1/content/index.css#L17-L39) in v5.1 that should help a little bit with that. It's a work in progress though so let me know if you find anything missing.
