### ISSUE TITLE
Blockquotes can not parse "space + space + Enter“

### ISSUE THREAD

**Issue by HeJiaJunPan** [simov/markdown-viewer#46]
"space + space + Enter“ can not exit the blockquotes,only"Enter + Enter" can exit the blockquotes

**Comment by simov** [comment]
:wave: @HeJiaJunPan, can you provide a code example to reproduce the issue using the following syntax:

<pre>
```markdown
> some code here
```
</pre>

**Comment by HeJiaJunPan** [comment]
```markdown
## Example  
> use "space + space + enter" wrap  
## display error  
```
"display error" show on blockquotes,

**Comment by HeJiaJunPan** [comment]
on Compiler Options - Remark,if use "commonmark"option,file display true.
GFM mode can not not parse "space + space + Enter“ for Blockquotes

**Comment by simov** [comment]
Enabling the `Commonmark` option for the Remark compiler seems to be working on my end. You can keep the `GFM` option enabled as well. The double space character at the end of the line doesn't seems to do anything.
