### ISSUE TITLE
Add support for checkboxes

### ISSUE THREAD

**Issue by arnoudplantinga** [simov/markdown-viewer#47]
I often use checkboxes in my Markdown, which are supported in Github markdown:

- [ ] Item

It would be nice if markdown-viewer also supported them!

**Comment by simov** [comment]
Hi, @arnoudplantinga, the Remark compiler supports GFM Task Lists:

![remark](https://user-images.githubusercontent.com/1694112/34883115-50ffb57a-f7c1-11e7-9a06-3be912b77e0f.png)

**Comment by arnoudplantinga** [comment]
Perfect, thank you! I think this solves this issue.
