### ISSUE TITLE
Vim code is not getting highlighted

### ISSUE THREAD

**Issue by i-give-up** [simov/markdown-viewer#51]
Here's a screenshot. Python code is highlighted fine but Vim code is not highlighted.

![simov-md_viewer-vim-highlight](https://user-images.githubusercontent.com/14156307/36960512-4b2d8a98-2082-11e8-9d81-1b16ac7a436b.png)

I checked and Vim is in prism's [list of supported languages](http://prismjs.com/#languages-list).

Let me know if you need more information.

Env: Chrome 64, Markdown Viewer 3.4

**Comment by simov** [comment]
Yep, not all Prism supported syntax definitions are included. I have a list of all included ones here: https://github.com/simov/markdown-viewer/blob/master/build/prism/prism.json

I'll add it in the next release.

**Comment by simov** [comment]
Markdown Viewer v5.1 now ships with all of the available languages in [prism](https://prismjs.com/#supported-languages).
