### ISSUE TITLE
Hot reload changes to markdown file

### ISSUE THREAD

**Issue by aehernandez** [simov/markdown-viewer#52]
My main use case for this extension has been to preview markdown files under development. It would be incredibly useful to have an option that would enable the plugin to rerender the file if the file has been changed.

As an alternative, rather than attempting to detect file changes, the extension can also rerender based on some period (1 second, 5, second) set by the user.

**Comment by simov** [comment]
Yes, this have been requested several times. The reload on interval is not best approach, I think. I'll have to think about more elegant way to do it.

**Comment by aehernandez** [comment]
I would agree it's not elegant, but definitely a useful feature.

If you want to avoid unnecessary reloads, you can hash the contents of the file, cache the result, and periodically recompute the hash. Then you can trigger a reload when the hash has changed. Of course, you're still effectively "polling" the file at some interval, but the user doesn't need to know that (unless it's made into an advanced setting). This seems like a low-time cost way of implementing this feature. 

Later, the reload mechanism can be changed with a better hook, and so the core functionality won't need to change.

**Comment by simov** [comment]
Sounds good. Thank you for your input! It will be implemented as option for sure.

**Comment by simov** [comment]
This feature landed in v3.6 Check out the Content tab in the popup, there is a new option called `autoreload`.
