### ISSUE TITLE
Support Multi-Byte Text

### ISSUE THREAD

**Issue by keito940** [simov/markdown-viewer#53]
Hi. I Am Japanese.

Mark Down Viewer Is **Very** Convenient.

..But, Markdown-Viewer Do Not Support Multi-Byte Text.

Support Plz.

**Comment by simov** [comment]
In v3.5 you can override the browser's built-in encoding detection for each allowed origin individually, and force it to use specific one from the Encoding dropdown menu.

Let me know if it works for you.
