### ISSUE TITLE
Mermaid and diagram support

### ISSUE THREAD

**Issue by inVisement** [simov/markdown-viewer#57]
Hi, Thanks for awesome extension. I was wondering how this extension can render mermaid (and other) diagrams, if possible at all. If not, would you add this feature to your development process.

Thank you
Ali

**Comment by simov** [comment]
Can you give me a link to it. I'll take a look.

**Comment by ValentinG0** [comment]
https://github.com/knsv/mermaid

**Comment by lonnywang** [comment]
https://mermaidjs.github.io/usage.html

**Comment by simov** [comment]
Thanks all, I'm yet to look at it, but I can assure you that it's on my TODO list :+1:

**Comment by RCVarley** [comment]
I don't know how much of this is transferable, but this vscode plugin (https://github.com/mjbvz/vscode-markdown-mermaid) adds mermaid support to the built in markdown preview feature.

**Comment by simov** [comment]
Mermaid diagrams are now supported in v4.0, note that you have to wrap your diagrams in fenced code blocks:

    ```mermaid
    sequenceDiagram
    ```

or

    ```mmd
    sequenceDiagram
    ```
