### ISSUE TITLE
support text/markdown as well as text/plain

### ISSUE THREAD

**Issue by vandenoever** [simov/markdown-viewer#58]
When a webserver sends `Content-Type: text/markdown`, Markdown viewer does not render the file. If the mimetype is `text/plain`, it does.

It would be nice if Markdown Viewer would also support the more precise mimetype.

**Comment by simov** [comment]
If the switch is enabled the extension will detects `text/markdown` and `text/x-markdown` content type for any allowed origin. 

`text/plain` is a generic mime type, and in that case you'll have to rely solely on the path matching regexp.

**Comment by simov** [comment]
One clarification: my previous comment was about Chrome, in Firefox the regular markdown mime type is converted to text/plain for each request, because Firefox can't handle markdown mime type correctly.
