### ISSUE TITLE
Chromium "open in new tab" bug

### ISSUE THREAD

**Issue by r888800009** [simov/markdown-viewer#61]
When I open a markdown file in the new tab, the extension will compile current tab, not the new tab.
Middle or right click then "open in new tab" all can Bug reproduction.

Version: 3.5
Chromium Version 67.0.3396.87 (Official Build) Arch Linux (64-bit)

**Comment by simov** [comment]
Thanks for the feedback. The extension currently renders only the currently active tab, meaning that you'll have to refresh the newly opened tab after you switch to it.

**Comment by fxpester** [comment]
when I open https://raw.githubusercontent.com/fxpester/androidSensors_to_rabbit/master/README.md
your application shows nothing, just white screen

**Comment by simov** [comment]
@fxpester that's another issue. You have to enable all remote origins manually or enable all of them if you want. Take a look at this short screencast: https://youtu.be/Wd-wHLm9MTI

**Comment by fxpester** [comment]
sure I enabled it first, without enabling I see just plain markdown.

**Comment by simov** [comment]
That's weird. Recently another user was complaining about similar issue and in his case it turned out to be a problem with another extension - Stylish. Can you try disabling your extensions and see if that make any difference?

**Comment by fxpester** [comment]
I disabled every extension/apps that could modify page content, still the result:
![image](https://user-images.githubusercontent.com/7628763/42088238-9a1753ee-7ba1-11e8-86d2-da5578ac20ef.png)

**Comment by simov** [comment]
You have to disable the _Content Security Policy_, there is a switch for it:
![screenshot from 2018-06-29 13-42-26](https://user-images.githubusercontent.com/1694112/42088493-4e08bf14-7ba2-11e8-90d8-0c92887f4c01.png)

**Comment by fxpester** [comment]
tricky interface you have! ok I disabled CSP and now have this results:
![image](https://user-images.githubusercontent.com/7628763/42089040-615fc128-7ba4-11e8-8ac7-8a287e2b9c58.png)
still just white screen

**Comment by simov** [comment]
I'm running out of ideas. Additionally you can inspect the background page of the extension for any potential errors. Let me know if you find anything.

**Comment by simov** [comment]
@r888800009 there was a bug when opening markdown document in new tab. The fix will be available in the next release. I'll let you know when I publish it :+1:

**Comment by simov** [comment]
@r888800009 this was fixed in v3.6 :tada:
