### ISSUE TITLE
Suggestion | Accept bitcoin and litecoin donations

### ISSUE THREAD

**Issue by fazlearefin** [simov/markdown-viewer#64]
I think alongside Paypal donations, you should also accept Bitcoin and Litecoin donations. This lets transfer of value bypassing the traditional banking system. Good luck.

**Comment by simov** [comment]
That's a good suggestion, @fazlearefin. I'm yet to set up all kinds of ways for donations, but I'll probably prioritize it now. PayPal doesn't seem to work for me anyway.
