### ISSUE TITLE
Options not working as of "Unexpected token on line 285"

### ISSUE THREAD

**Issue by garex** [simov/markdown-viewer#65]
Version 56.0.2924.87 (64-bit)

Seems like it not likes trailing commas:

https://github.com/simov/markdown-viewer/blob/102a2cdac69a43a143fdcd85292f7ef8dcb4be56/content/options.js#L284

**Comment by simov** [comment]
Thanks for the heads-up! That's Chrome 56 right? Trailing commas should be available from [Chrome 58](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) onward.

**Comment by simov** [comment]
Fixed in #85
