### ISSUE TITLE
Make some useful setups as default settings

### ISSUE THREAD

**Issue by Erich-Chen** [simov/markdown-viewer#67]
Hi @simov I mainly come around to say thank you for such a great chrome extension. It helps me to read my own github repo perfect where there is a lot of math equations in it. 

It took me quite some time to understand and set up it correctly to render math equations for github. 
For `Exclude Origin` part, it took me 30 minutes to understand that I shall leave "MATCH" option blank :-( my stupid. 

So how do you think to make default set up fitting github? 
For example, I think below settings are very useful. 
1. Exclude Origin "github.com"; 
2. Allow Origin "raw.githubusercontent.com"; 
3. Enable autoreload / mathjax / scroll / toc. 
4. Enable github flavored markdown and breaks. 

Thank you so much developing Markdown Viewer a perfect tool.

**Comment by simov** [comment]
Excluding of origins in Markdown Viewer v5.1 is no longer needed. It is still there and it works the same way as before, but the content detection algorithm itself has a much better chance now to determine if content is supposed to be rendered or not. Which was the main issue for a lot of people.

Outside of that I may consider changing some of the default content options as well, but for now they will stay as they are. I want people to go there and find them, and know where they are, plus I don't know if absolutely everyone would need all of those options enabled, and enabling all of them might slow down a little bit the initial loading time too.
