### ISSUE TITLE
UTF-8 default

### ISSUE THREAD

**Issue by neenko** [simov/markdown-viewer#7]
Could you make UTF the default encoding for HTML preview? Or at least an option to set it.
Things like
![image](https://cloud.githubusercontent.com/assets/694898/18631419/31af227e-7e72-11e6-90eb-0be5a4d6726c.png)
would then display like
![image](https://cloud.githubusercontent.com/assets/694898/18631440/4a5c7d8a-7e72-11e6-8c89-ded46f318834.png)

**Comment by simov** [comment]
My browser always renders in UTF-8 so I wasn't aware of the issue. I'll take a look at it.

**Comment by simov** [comment]
Just released version 2.2 which hopefully fixes the issue. It works with my tests.

Thank you for letting me know about this issue. Let me know if the problem is still there.

Keep in mind that you'll have to wait for about an hour before the new release appears in chromestore and auto updates.

**Comment by simov** [comment]
Also @neenko let me know if this release fixes the issue for you :)

**Comment by neno-giscloud** [comment]
@simov yes it does, thank you!

**Comment by neenko** [comment]
@simov yep, you fixed it! thanks!

**Comment by bobbykjack** [comment]
I have this issue with the current version. I tried to hack content/index.js to inject the appropriate `<meta charset="utf-8">` element, but it looks like this doesn't work at runtime. A fix would need access to the html source, which I cannot locate.

**Comment by simov** [comment]
Hi @bobbykjack, you can add it here https://github.com/simov/markdown-viewer/blob/5.3/content/index.js#L144:
```js
var meta = document.createElement('meta')
meta.charset = 'utf-8'
$('head').insertBefore(meta, document.head.firstChild)
meta.setAttribute('charset', 'utf-8')
```

though according to this thread https://stackoverflow.com/questions/12560027/set-charset-meta-tag-with-javascript it won't have any effect.

I'd be curious to know what your use case is, probably you can share some details on how to reproduce the issue as this thread is quite old too.

**Comment by bobbykjack** [comment]
Hi there. I'll give that a go. The only difference is the setting of the charset property in addition to the setAttribute() call — I'll see if that has any effect.

My use case is simply wanting unicode characters (like dashes, quotation marks, etc.) to render properly instead of degrading to ascii.

**Comment by bobbykjack** [comment]
OK, I've found a workaround — tbh, this might be 'the right thing' to do in the first place. I've set my web server (apache) to serve markdown files as utf-8.
