### ISSUE TITLE
symbols (even ascii) not rendered

### ISSUE THREAD

**Issue by DoctorSubtilis** [simov/markdown-viewer#74]
I really appreciate this extension, but I regret that it does not recognize certain symbols, like `&#58773;` or similar.  
I hope in future this will be possible. Thank you

**Comment by DoctorSubtilis** [comment]
Eureka! Add font-family: <span style="font-family: opensymbol">&#58773;</span>. So it works!

**Comment by simov** [comment]
Thanks for the feedback! My plan for the next release is to allow the users to include additional styles. That will solve this problem.

**Comment by simov** [comment]
Custom styles are no longer on the roadmap, but I'm glad that you found a way of solving your problem in the first place.
