### ISSUE TITLE
Tries to fetch favicon.ico and fails loading page but the site doesn't have a fav icon :(

### ISSUE THREAD

**Issue by vivekragunathan** [simov/markdown-viewer#75]
![image](https://user-images.githubusercontent.com/292160/50568428-898a0700-0d06-11e9-8ece-126cfdaf679d.png)

I am trying to view a markdown file from amazon S3 link, and the add-on fails loading because of the error attached. I think if the favicon fetch fails, it should be ignored and the page should be loaded.

**Comment by simov** [comment]
Are you sure you have enabled that origin through the Advanced Options page? Just checking.

**Comment by simov** [comment]
Failing to load the favicon should not affect how the extension works.
