### ISSUE TITLE
Extension fails to load md file and crashes in chrome incognito window

### ISSUE THREAD

**Issue by VivekRagunathan** [simov/markdown-viewer#76]
I am trying to open a local `.md` file and the extension crashes with a popup saying _the extension crashed, click here to reload the extension_.

**Comment by simov** [comment]
That's interesting. I just enabled the extension for incognito mode and it crashes. Thanks for the feedback, I'll definitely have a look at it!

**Comment by simov** [comment]
Just tested on Chrome 76, I can no longer reproduce the issue.
