### ISSUE TITLE
[Feature Request] Nice to able to modify the CSS of existing themes or clone and update the styles

### ISSUE THREAD

**Issue by vivekragunathan** [simov/markdown-viewer#77]

**Comment by simov** [comment]
Yep, the plan is to enable custom styles in the next release.

**Comment by itcastWsy** [comment]
what time finish   i expect

**Comment by silver-dragon** [comment]
Yes, I would also find this feature to be very useful.

**Comment by tmpm697** [comment]
Any news on this? I also want to modify some colors.

**Comment by simov** [comment]
Hi, the support for this feature was indeed abandoned, however, there is a good news too and that is that in Markdown Viewer v5 we have 30 new themes and all of them are looking great. There are both light and dark themes, but also quite a few that support the prefer dark auto mode too. So the approach that I took with this was to make sure we have a good amount of high quality themes that are also fixed (if needed) to work seamlessly in Markdown Viewer.

You can download the latest release from the Chrome Web Store or the [releases](https://github.com/simov/markdown-viewer/releases) section here.

The other option of using an additional extension to update those themes is still valid.
