### ISSUE TITLE
Is it possible to hide text between braces?

### ISSUE THREAD

**Issue by DoctorSubtilis** [simov/markdown-viewer#80]
I uso pandoc filters to convert md files in odt, and that filters use a proprietary syntax, i.p.  

    {custom-styles="namestyle"}.  
It's not a bug, but a question: there is a way to hide, in MD viewer that text between braces?
Thank you

**Comment by simov** [comment]
Currently there is no way to hide such text. If it's some sort of a standard, then there could be a plugin for the underlying Markdown parser that I'm using.

**Comment by DoctorSubtilis** [comment]
Thank you. I don't believe that is a standard, but a proprietary code. You can see [here](https://github.com/jzeneto/pandoc-odt-filters).

**Comment by simov** [comment]
Markdown Viewer v5.2 got released with a new default compiler called markdown-it and an option called `attr` that addresses this issue https://github.com/simov/markdown-viewer#compiler-options
