### ISSUE TITLE
Advanced Options in Chrome shows a blank page

### ISSUE THREAD

**Issue by Eontech** [simov/markdown-viewer#81]
Clicking on Advanced Options renders a page with a header + footer, but is blank in between.

So I cannot change anything, like allow origin, etc.

**Comment by simov** [comment]
Which version of Chrome do you use?

**Comment by Eontech** [comment]
Thanks for getting back so quick:

I'm on 53.0.2785.116 (64-bit), and you're right I'm quite sure that's the reason.
Google's constant messing with my settings, is the reason they're prevented from updating this!

I have everything I need + the extensions I use work fine.

Usually if there is any anomaly I fall back on Firefox.  But you're FF extension has no Advanced options.

**Comment by simov** [comment]
Access to local files doesn't work on Firefox. There are some workarounds that might work with various success. Check out this issue: https://github.com/simov/markdown-viewer/issues/54

The easiest way to workaround the file access issue in Firefox is to have a file server running on some port on localhost. Then you can allow localhost and read your markdown files from there.

As for the options page not working on Chrome - you can open up the devtools and see the error in the console. It should be some language feature missing. I'm trying to support older versions of Chrome, but at the same time I'm not transpiling my code, so at some point breaking changes may occur in much older versions of the browser.

**Comment by Eontech** [comment]
With Firefox I have local file access working fine via (file://...) url in my version (Waterfox 57 actually) by default.  It is the access through any kind of web-server that doesn't work.  Same behaviour as the 'Origin' issue in Chrome.

Here's the my Chrome: dev-console JS error.
options.js:285 Uncaught SyntaxError: Unexpected token )

I noticed line 286 is referencing i.material-icons class.  Not sure if it could be that, but Chrome's forced use of their Material-icons (a truly horrendous eye-sore on mac) was the red line for me.

I understand your point about support for older versions of Chrome.  Personally speaking, As long as I can get to the required settings, I have little care for how pretty the page displaying the controls, looks.

I am also happy to modify any setting / JS file etc locally to get this working.

**Comment by Eontech** [comment]
With Firefox I have local file access working fine via (file://...) url in my version (Waterfox 57 actually) by default.  It is the access through any kind of web-server that doesn't work.  Same behaviour as the 'Origin' issue in Chrome.

Here's the Chrome: dev-console JS error.
options.js:285 Uncaught SyntaxError: Unexpected token )

I noticed line 286 is referencing i.material-icons class.  Not sure if it could be that, but Chrome's forced use of their Material-icons (a truly horrendous eye-sore on mac) was the red line for me.

I understand your point about support for older versions of Chrome.  Personally speaking, As long as I can get to the required settings, I have little care for how pretty the page displaying the controls, looks.

I am also happy to modify any setting / JS file etc locally to get this working.

**Comment by simov** [comment]
What I meant by file access was that if you try to open a markdown file like `file:///.../file.md` FireFox opens up a popup - not the file. So unless the file is actually opened the extension can't access it.

I'm not sure about the error, it might be as simple as extra comma `,` because the older versions didn't like it.

I'll take a look, but in the meantime you can clone the repo and load it as unpacked extension - there is info about it in the docs. Then you can try to fix the issue in the UI (if it's something small).

**Comment by Eontech** [comment]
Thanks for the tip.  The advanced page shows fine now, on my tests.  
The details are in my pull request.

I've added now my localhost:port but still get prompted to download *.md files, but that's unrelated to this issue which is now fixed.

**Comment by simov** [comment]
Thanks @Eontech, I'll take a look at it. Hopefully I won't put commas in similar places again.
