### ISSUE TITLE
Extended Markdown support

### ISSUE THREAD

**Issue by stdedos** [simov/markdown-viewer#84]
Is there some compiler that offers Extended Markdown support?

(https://www.markdownguide.org/extended-syntax/)

**Comment by stdedos** [comment]
> Which feature exactly is missing for you?

The (supposedly) missing feature was "Footnotes", however ...

> Remark also supports footnotes through an option.

... Oops! I somehow missed that options changed when changing the compiler. Apologies 😞 

-----
 
> You can play around with the supported syntax using [this file](https://raw.githubusercontent.com/simov/markdown-syntax/master/syntax.md), download the repo locally or allow the `raw.githubusercontent.com` origin.

High-jacking my own thread: 

With:
![image](https://user-images.githubusercontent.com/133706/51871319-bb6ea780-235e-11e9-944f-4ea0832d32cd.png)

https://raw.githubusercontent.com/simov/markdown-syntax/master/syntax.md is giving me:
![image](https://user-images.githubusercontent.com/133706/51871297-aabe3180-235e-11e9-9804-a5bdd82a637a.png)

Am I missing something?

**Comment by stdedos** [comment]
@simov so ... is it now correct?

I first turned on the CSP, then I loaded the website:
![image](https://user-images.githubusercontent.com/133706/51933104-3d1b0f80-2409-11e9-9178-572d9a260b32.png)

**Comment by simov** [comment]
Yes it seems correct. Can you tell me your Chrome version and OS probably? Everything works as expected on my end. Also can you try to disable all other extensions if you have any, and try again?

**Comment by stdedos** [comment]
I will check for conflicting extensions on my Win 10 Chrome, since 

```
Version 71.0.3578.98 (Official Build) (64-bit)
Ubuntu 16.04.5
```

works as expected.
