### ISSUE TITLE
Empty table cells are not rendered correctly

### ISSUE THREAD

**Issue by MarcoMiltenburg** [simov/markdown-viewer#91]
I noticed that empty table cells are not rendered correctly. When a table starts with an empty cell the whole table fails to render. For example:

```
|   | Test    |
|---|---------|
| 1 | Problem |
```
should render as:

|| Test |
|--|--|
| 1 | Problem |

as it does here on GitHub but it doesn't. It renders as:

![image](https://user-images.githubusercontent.com/6213937/55156610-b1003c80-515a-11e9-8ccc-233a4e695ecf.png)

Adding or removing spaces does not make a difference.

Empty cells on the middle of the table are just ignored and cause cells to shift and the pipe synbol to be part of the text in the cell.  Example:

```
| Column 1 | Column 2 | Column 3  |
|----------|----------|-----------|
| This     | Is       | Correct   |
|          | Rendered | Incorrect |
```

should render as:

| Column 1 | Column 2 | Column 3  |
|----------|----------|-----------|
| This     | Is       | Correct   |
|          | Rendered | Incorrect |

but renders as:

![image](https://user-images.githubusercontent.com/6213937/55156631-bf4e5880-515a-11e9-9f95-8d7431404dfa.png)

**Comment by MarcoMiltenburg** [comment]
Update: seems this is specific to the Marked compiler. It works fine with Remark. The issue is [already fixed](https://github.com/markedjs/marked/pull/1262) in Marked.

**Comment by smileham** [comment]
Still seeing this issue, both for Marked and Remark compilers.

**Comment by simov** [comment]
Both marked and remark have been updated in v3.7 and issue seems to be fixed. Let me know if you have any issues.
