### ISSUE TITLE
Usage and possible configuration question

### ISSUE THREAD

**Issue by steinhaug** [simov/markdown-viewer#92]
**Update, sollution to my question found:**
I found the sollution I was looking for here so this question can be closed. https://github.com/markedjs/marked

**Original message:**
I hope it's ok to ask here, I couldnt find another place. I am wondering if this markdown-viewer can be used as a "live preview" from a markdown editable form field.

I have an "markdown editor", basically a text field using Codemirror js library as enhanced markdown visualization, however my cuistomer does not like this and would like a full preview of the page as it will look after in real life.

Will this browserplugin be able to work so that I can render the final HTML from the markdown directly in the browser? For some reason I expect this plugin to be faster and cleaner than a javascript library for rendering the HTML from the Markdown would.

Say domain with editor is //domain.com/admin/editor.php and text field being edited with markdown syntax has an ID of "markdown-textarea". I would like the compiled final HTML from the Markdown syntax in a div with ID of "markdown-preview". How do I configure the plugin so that:

a) it reads the markdown-textarea and compiles into markdown-preview each 2-3 seconds.
b) feed the markdown-viewer with code to compile and return into the browser for preview

Hopefully someone understands what I am getting at here,

**Comment by simov** [comment]
:+1:
