### ISSUE TITLE
Preferences window keeps growing

### ISSUE THREAD

**Issue by jfcg** [simov/markdown-viewer#99]
On firefox 69.0.1 on Linux, addon v3.6 from addon.mozilla.org, preference window keeps growing down..

**Comment by simov** [comment]
Yep, saw that. The advanced options page was never designed to work inside another page. Might because of the sticky footer, I have to review the styles at some point.

**Comment by simov** [comment]
Hey, @jfcg, was that fixed in Firefox?

**Comment by jfcg** [comment]
i was closing old/stale issues. didnt try..
